// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Vehicle_Inspection;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Seller_Details</b><br>
 * Generated     : <b>2015/09/21 10:59:13</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  September 21, 2015
 * @author horned
 */
public abstract class Seller_DetailsHelper extends Utilities.AA_SuperHelper
{
	/**
	 * county: with default state.
	 *		.id : {{config.prefix}}County
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : county
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected TextGuiTestObject address_county() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("address_county"));
	}
	/**
	 * county: with specific test context and state.
	 *		.id : {{config.prefix}}County
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : county
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected TextGuiTestObject address_county(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("address_county"), anchor, flags);
	}
	
	/**
	 * lineOne: with default state.
	 *		.id : RegularExpression(LineOne)
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : lineOne
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected TextGuiTestObject address_lineOne() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("address_lineOne"));
	}
	/**
	 * lineOne: with specific test context and state.
	 *		.id : RegularExpression(LineOne)
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : lineOne
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected TextGuiTestObject address_lineOne(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("address_lineOne"), anchor, flags);
	}
	
	/**
	 * lineTwo: with default state.
	 *		.id : {{config.prefix}}LineTwo
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : lineTwo
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected TextGuiTestObject address_lineTwo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("address_lineTwo"));
	}
	/**
	 * lineTwo: with specific test context and state.
	 *		.id : {{config.prefix}}LineTwo
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : lineTwo
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected TextGuiTestObject address_lineTwo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("address_lineTwo"), anchor, flags);
	}
	
	/**
	 * townOrCity: with default state.
	 *		.id : {{config.prefix}}Town
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : townOrCity
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected TextGuiTestObject address_townOrCity() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("address_townOrCity"));
	}
	/**
	 * townOrCity: with specific test context and state.
	 *		.id : {{config.prefix}}Town
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : townOrCity
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected TextGuiTestObject address_townOrCity(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("address_townOrCity"), anchor, flags);
	}
	
	/**
	 * Continuesubmit: with default state.
	 *		.id : continue
	 * 		.type : submit
	 * 		.value : My details are correct and I’m happy to continue
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject continue_submit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("continue_submit"));
	}
	/**
	 * Continuesubmit: with specific test context and state.
	 *		.id : continue
	 * 		.type : submit
	 * 		.value : My details are correct and I’m happy to continue
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject continue_submit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("continue_submit"), anchor, flags);
	}
	
	/**
	 * FindYourFullAddresssubmit: with default state.
	 *		.id : addressSubmit
	 * 		.type : submit
	 * 		.value : Find your full address
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected GuiTestObject find_Address_submit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("find_Address_submit"));
	}
	/**
	 * FindYourFullAddresssubmit: with specific test context and state.
	 *		.id : addressSubmit
	 * 		.type : submit
	 * 		.value : Find your full address
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected GuiTestObject find_Address_submit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("find_Address_submit"), anchor, flags);
	}
	
	/**
	 * customerDetails: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : ctrl.details
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected GuiTestObject form_sellerDetails() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_sellerDetails"));
	}
	/**
	 * customerDetails: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : ctrl.details
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected GuiTestObject form_sellerDetails(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_sellerDetails"), anchor, flags);
	}
	
	/**
	 * customer_phone: with default state.
	 *		.id : customer_phone
	 * 		.title : 
	 * 		.class : Html.INPUT.tel
	 * 		.name : customer_phone
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_customer_phone() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_customer_phone"));
	}
	/**
	 * customer_phone: with specific test context and state.
	 *		.id : customer_phone
	 * 		.title : 
	 * 		.class : Html.INPUT.tel
	 * 		.name : customer_phone
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_customer_phone(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_customer_phone"), anchor, flags);
	}
	
	/**
	 * vendor_phone: with default state.
	 *		.id : vendor_phone
	 * 		.title : 
	 * 		.class : Html.INPUT.tel
	 * 		.name : vendor_phone
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_vendor_phone() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_vendor_phone"));
	}
	/**
	 * vendor_phone: with specific test context and state.
	 *		.id : vendor_phone
	 * 		.title : 
	 * 		.class : Html.INPUT.tel
	 * 		.name : vendor_phone
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_vendor_phone(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_vendor_phone"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"), anchor, flags);
	}
	
	/**
	 * EuropeanBreakdownCoverAA: with default state.
	 *		.title : RegularExpression(inspections)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(inspections)
	 */
	protected DocumentTestObject inspection() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("inspection"));
	}
	/**
	 * EuropeanBreakdownCoverAA: with specific test context and state.
	 *		.title : RegularExpression(inspections)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(inspections)
	 */
	protected DocumentTestObject inspection(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("inspection"), anchor, flags);
	}
	
	/**
	 * Miss: with default state.
	 *		.id : customer_title_miss_label
	 * 		.value :  Miss 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 5
	 */
	protected GuiTestObject label_miss() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_miss"));
	}
	/**
	 * Miss: with specific test context and state.
	 *		.id : customer_title_miss_label
	 * 		.value :  Miss 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 5
	 */
	protected GuiTestObject label_miss(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_miss"), anchor, flags);
	}
	
	/**
	 * Mr: with default state.
	 *		.id : customer_title_mr_label
	 * 		.value :  Mr 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 3
	 */
	protected GuiTestObject label_mr() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mr"));
	}
	/**
	 * Mr: with specific test context and state.
	 *		.id : customer_title_mr_label
	 * 		.value :  Mr 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 3
	 */
	protected GuiTestObject label_mr(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mr"), anchor, flags);
	}
	
	/**
	 * Mrs: with default state.
	 *		.id : customer_title_mrs_label
	 * 		.value :  Mrs 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 4
	 */
	protected GuiTestObject label_mrs() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mrs"));
	}
	/**
	 * Mrs: with specific test context and state.
	 *		.id : customer_title_mrs_label
	 * 		.value :  Mrs 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 4
	 */
	protected GuiTestObject label_mrs(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mrs"), anchor, flags);
	}
	
	/**
	 * Ms: with default state.
	 *		.id : customer_title_ms_label
	 * 		.value :  Ms 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 6
	 */
	protected GuiTestObject label_ms() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_ms"));
	}
	/**
	 * Ms: with specific test context and state.
	 *		.id : customer_title_ms_label
	 * 		.value :  Ms 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 6
	 */
	protected GuiTestObject label_ms(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_ms"), anchor, flags);
	}
	
	/**
	 * ngApp: with default state.
	 *		.id : ng-app
	 * 		.title : 
	 * 		.class : Html.HTML
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected GuiTestObject ngApp() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ngApp"));
	}
	/**
	 * ngApp: with specific test context and state.
	 *		.id : ng-app
	 * 		.title : 
	 * 		.class : Html.HTML
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected GuiTestObject ngApp(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ngApp"), anchor, flags);
	}
	
	/**
	 * customer_first_name: with default state.
	 *		.id : customer_first_name
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : customer_first_name
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_customer_first_name() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_customer_first_name"));
	}
	/**
	 * customer_first_name: with specific test context and state.
	 *		.id : customer_first_name
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : customer_first_name
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_customer_first_name(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_customer_first_name"), anchor, flags);
	}
	
	/**
	 * customer_surname: with default state.
	 *		.id : customer_surname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : customer_surname
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_customer_surname() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_customer_surname"));
	}
	/**
	 * customer_surname: with specific test context and state.
	 *		.id : customer_surname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : customer_surname
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_customer_surname(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_customer_surname"), anchor, flags);
	}
	
	/**
	 * email: with default state.
	 *		.id : email
	 * 		.title : 
	 * 		.class : Html.INPUT.email
	 * 		.name : email
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_email() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_email"));
	}
	/**
	 * email: with specific test context and state.
	 *		.id : email
	 * 		.title : 
	 * 		.class : Html.INPUT.email
	 * 		.name : email
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_email(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_email"), anchor, flags);
	}
	
	/**
	 * lineOne: with default state.
	 *		.id : addressLineOne
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : lineOne
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_lineOne() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_lineOne"));
	}
	/**
	 * lineOne: with specific test context and state.
	 *		.id : addressLineOne
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : lineOne
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_lineOne(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_lineOne"), anchor, flags);
	}
	
	/**
	 * postcode: with default state.
	 *		.id : addressPostcode
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : postcode
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_postcode() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_postcode"));
	}
	/**
	 * postcode: with specific test context and state.
	 *		.id : addressPostcode
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : postcode
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_postcode(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_postcode"), anchor, flags);
	}
	
	/**
	 * vendor_name: with default state.
	 *		.id : vendor_name
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : vendor_name
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_vendor_name() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_vendor_name"));
	}
	/**
	 * vendor_name: with specific test context and state.
	 *		.id : vendor_name
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : vendor_name
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_vendor_name(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_vendor_name"), anchor, flags);
	}
	
	

	protected Seller_DetailsHelper()
	{
		setScriptName("Vehicle_Inspection.Seller_Details");
	}
	
}

