// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Vehicle_Inspection;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Vehicle_Details_Location</b><br>
 * Generated     : <b>2015/09/24 15:23:26</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  September 24, 2015
 * @author horned
 */
public abstract class Vehicle_Details_LocationHelper extends Utilities.AA_SuperHelper
{
	/**
	 * PleaseGiveMeAQuotesubmit: with default state.
	 *		.id : continue
	 * 		.type : submit
	 * 		.value : Please give me a quote
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_pleaseGiveMeAQuote() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_pleaseGiveMeAQuote"));
	}
	/**
	 * PleaseGiveMeAQuotesubmit: with specific test context and state.
	 *		.id : continue
	 * 		.type : submit
	 * 		.value : Please give me a quote
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_pleaseGiveMeAQuote(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_pleaseGiveMeAQuote"), anchor, flags);
	}
	
	/**
	 * AccordingToThePostcodeYouVeGivenUsLL552AZIsInAArea: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_accordingToThePostcodeYou() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_accordingToThePostcodeYou"));
	}
	/**
	 * AccordingToThePostcodeYouVeGivenUsLL552AZIsInAArea: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_accordingToThePostcodeYou(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_accordingToThePostcodeYou"), anchor, flags);
	}
	
	/**
	 * ctrlVehiclelocation: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : ctrl.vehiclelocation
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_ctrlVehiclelocation() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_ctrlVehiclelocation"));
	}
	/**
	 * ctrlVehiclelocation: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : ctrl.vehiclelocation
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_ctrlVehiclelocation(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_ctrlVehiclelocation"), anchor, flags);
	}
	
	/**
	 * ngApp: with default state.
	 *		.id : ng-app
	 * 		.title : 
	 * 		.class : Html.HTML
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_ngApp() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_ngApp"));
	}
	/**
	 * ngApp: with specific test context and state.
	 *		.id : ng-app
	 * 		.title : 
	 * 		.class : Html.HTML
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_ngApp(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_ngApp"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"), anchor, flags);
	}
	
	/**
	 * reg: with default state.
	 *		.id : reg
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : reg
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_reg() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_reg"));
	}
	/**
	 * reg: with specific test context and state.
	 *		.id : reg
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : reg
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_reg(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_reg"), anchor, flags);
	}
	
	/**
	 * vendor_postcode: with default state.
	 *		.id : vendor_postcode
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : vendor_postcode
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_vendor_postcode() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_vendor_postcode"));
	}
	/**
	 * vendor_postcode: with specific test context and state.
	 *		.id : vendor_postcode
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : vendor_postcode
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_vendor_postcode(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_vendor_postcode"), anchor, flags);
	}
	
	

	protected Vehicle_Details_LocationHelper()
	{
		setScriptName("Vehicle_Inspection.Vehicle_Details_Location");
	}
	
}

