// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Aggregators.XML;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Copy_RAW_Browser_XML</b><br>
 * Generated     : <b>2015/03/19 14:02:03</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  March 19, 2015
 * @author horned
 */
public abstract class Copy_RAW_Browser_XMLHelper extends Utilities.AA_SuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * raw_XML: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(theaa\.com/aaservlet)
	 */
	protected DocumentTestObject document_raw_XML() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_raw_XML"));
	}
	/**
	 * raw_XML: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(theaa\.com/aaservlet)
	 */
	protected DocumentTestObject document_raw_XML(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_raw_XML"), anchor, flags);
	}
	
	

	protected Copy_RAW_Browser_XMLHelper()
	{
		setScriptName("Aggregators.XML.Copy_RAW_Browser_XML");
	}
	
}

