// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Aggregators;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Generate_Quote</b><br>
 * Generated     : <b>2015/03/06 09:02:27</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  March 06, 2015
 * @author horned
 */
public abstract class Generate_QuoteHelper extends Utilities.AA_SuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Escapebutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Escape
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_escapebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_escapebutton"));
	}
	/**
	 * Escapebutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Escape
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_escapebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_escapebutton"), anchor, flags);
	}
	
	/**
	 * Sendbutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Send
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_sendbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_sendbutton"));
	}
	/**
	 * Sendbutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Send
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_sendbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_sendbutton"), anchor, flags);
	}
	
	/**
	 * Unescapebutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Unescape
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject button_unescapebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_unescapebutton"));
	}
	/**
	 * Unescapebutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : Unescape
	 * 		.title : 
	 * 		.class : Html.INPUT.button
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject button_unescapebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_unescapebutton"), anchor, flags);
	}
	
	/**
	 * DOMExplorer: with default state.
	 *		.title : DOM Explorer
	 * 		.class : Html.HtmlDocument
	 * 		.url : res://C:\Program Files\Internet Explorer\F12Resources.dll/23/dom/dom.html
	 */
	protected DocumentTestObject document_domExplorer() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_domExplorer"));
	}
	/**
	 * DOMExplorer: with specific test context and state.
	 *		.title : DOM Explorer
	 * 		.class : Html.HtmlDocument
	 * 		.url : res://C:\Program Files\Internet Explorer\F12Resources.dll/23/dom/dom.html
	 */
	protected DocumentTestObject document_domExplorer(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_domExplorer"), anchor, flags);
	}
	
	/**
	 * httpWwwTheaaComAaservletInsuranceXMLQuoteXmlString3C3: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://www.theaa.com/aaservlet/InsuranceXMLQuote?xmlString=%3C%3Fxml%20version%3 ...
	 */
	protected DocumentTestObject document_httpWwwTheaaComAaserv() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpWwwTheaaComAaserv"));
	}
	/**
	 * httpWwwTheaaComAaservletInsuranceXMLQuoteXmlString3C3: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://www.theaa.com/aaservlet/InsuranceXMLQuote?xmlString=%3C%3Fxml%20version%3 ...
	 */
	protected DocumentTestObject document_httpWwwTheaaComAaserv(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpWwwTheaaComAaserv"), anchor, flags);
	}
	
	/**
	 * _AAInsuranceReplyNs2NoNamespaceSchemaLocationHttpWwwThea: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link__AAInsuranceReplyNs2NoNam() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__AAInsuranceReplyNs2NoNam"));
	}
	/**
	 * _AAInsuranceReplyNs2NoNamespaceSchemaLocationHttpWwwThea: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link__AAInsuranceReplyNs2NoNam(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__AAInsuranceReplyNs2NoNam"), anchor, flags);
	}
	
	/**
	 * _instalmentInsurernameAcromasAATotalamount44234Noin: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link__instalmentInsurernameAcr() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__instalmentInsurernameAcr"));
	}
	/**
	 * _instalmentInsurernameAcromasAATotalamount44234Noin: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link__instalmentInsurernameAcr(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__instalmentInsurernameAcr"), anchor, flags);
	}
	
	/**
	 * _instalmentInsurernameAcromasAATotalamount44234Noin: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 5
	 */
	protected GuiTestObject link__instalmentInsurernameAcr2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__instalmentInsurernameAcr2"));
	}
	/**
	 * _instalmentInsurernameAcromasAATotalamount44234Noin: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 5
	 */
	protected GuiTestObject link__instalmentInsurernameAcr2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__instalmentInsurernameAcr2"), anchor, flags);
	}
	
	/**
	 * _instalmentInsurernameAcromasAATotalamount47189Noin: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 7
	 */
	protected GuiTestObject link__instalmentInsurernameAcr3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__instalmentInsurernameAcr3"));
	}
	/**
	 * _instalmentInsurernameAcromasAATotalamount47189Noin: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 7
	 */
	protected GuiTestObject link__instalmentInsurernameAcr3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__instalmentInsurernameAcr3"), anchor, flags);
	}
	
	/**
	 * _instalmentInsurernameAcromasAATotalamount47189Noin: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 9
	 */
	protected GuiTestObject link__instalmentInsurernameAcr4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__instalmentInsurernameAcr4"));
	}
	/**
	 * _instalmentInsurernameAcromasAATotalamount47189Noin: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 9
	 */
	protected GuiTestObject link__instalmentInsurernameAcr4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__instalmentInsurernameAcr4"), anchor, flags);
	}
	
	/**
	 * _motor: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link__motor() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__motor"));
	}
	/**
	 * _motor: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link__motor(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__motor"), anchor, flags);
	}
	
	/**
	 * _quoteInsurernameAcromasAAVolexcess100TypeUnprotec: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link__quoteInsurernameAcromasA() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__quoteInsurernameAcromasA"));
	}
	/**
	 * _quoteInsurernameAcromasAAVolexcess100TypeUnprotec: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link__quoteInsurernameAcromasA(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__quoteInsurernameAcromasA"), anchor, flags);
	}
	
	/**
	 * _quoteInsurernameAcromasAAVolexcess100TypeProtecte: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	protected GuiTestObject link__quoteInsurernameAcromasA2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__quoteInsurernameAcromasA2"));
	}
	/**
	 * _quoteInsurernameAcromasAAVolexcess100TypeProtecte: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	protected GuiTestObject link__quoteInsurernameAcromasA2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__quoteInsurernameAcromasA2"), anchor, flags);
	}
	
	/**
	 * _quoteInsurernameAcromasAAVolexcess100TypeUnprotec: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	protected GuiTestObject link__quoteInsurernameAcromasA3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__quoteInsurernameAcromasA3"));
	}
	/**
	 * _quoteInsurernameAcromasAAVolexcess100TypeUnprotec: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	protected GuiTestObject link__quoteInsurernameAcromasA3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__quoteInsurernameAcromasA3"), anchor, flags);
	}
	
	/**
	 * _quoteInsurernameAcromasAAVolexcess100TypeProtecte: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 8
	 */
	protected GuiTestObject link__quoteInsurernameAcromasA4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__quoteInsurernameAcromasA4"));
	}
	/**
	 * _quoteInsurernameAcromasAAVolexcess100TypeProtecte: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.a
	 * 		.name : 
	 * 		.classIndex : 8
	 */
	protected GuiTestObject link__quoteInsurernameAcromasA4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__quoteInsurernameAcromasA4"), anchor, flags);
	}
	
	/**
	 * pl: with default state.
	 *		.text : localhost:7001 localhost prelive1.theaa.com prelive2.theaa.com prelive3.theaa.co ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : pl
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_pl() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_pl"));
	}
	/**
	 * pl: with specific test context and state.
	 *		.text : localhost:7001 localhost prelive1.theaa.com prelive2.theaa.com prelive3.theaa.co ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : pl
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_pl(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_pl"), anchor, flags);
	}
	
	/**
	 * theaaCom: with default state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : theaa.com
	 */
	protected BrowserTabTestObject pageTab_theaaCom() 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab_theaaCom"));
	}
	/**
	 * theaaCom: with specific test context and state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : theaa.com
	 */
	protected BrowserTabTestObject pageTab_theaaCom(TestObject anchor, long flags) 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab_theaaCom"), anchor, flags);
	}
	
	/**
	 * escapedpayload: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : escapedpayload
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_escapedpayload() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_escapedpayload"));
	}
	/**
	 * escapedpayload: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : escapedpayload
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_escapedpayload(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_escapedpayload"), anchor, flags);
	}
	
	/**
	 * unescapedpayload: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : unescapedpayload
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_unescapedpayload() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_unescapedpayload"));
	}
	/**
	 * unescapedpayload: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : unescapedpayload
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_unescapedpayload(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_unescapedpayload"), anchor, flags);
	}
	
	/**
	 * xmlString: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : xmlString
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_xmlString() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_xmlString"));
	}
	/**
	 * xmlString: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : xmlString
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_xmlString(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_xmlString"), anchor, flags);
	}
	
	

	protected Generate_QuoteHelper()
	{
		setScriptName("Aggregators.Generate_Quote");
	}
	
}

