// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Motor_MK2;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Payment_Submit</b><br>
 * Generated     : <b>2015/06/08 11:06:41</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  June 08, 2015
 * @author horned
 */
public abstract class Payment_SubmitHelper extends Utilities.AA_SuperHelper
{
	/**
	 * Submit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Submit
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_submit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_submit"));
	}
	/**
	 * Submit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Submit
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_submit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_submit"), anchor, flags);
	}
	
	/**
	 * _XmlVersion10EncodingUTF8ThreeDSecureMessageId: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__Xml_Content() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__Xml_Content"));
	}
	/**
	 * _XmlVersion10EncodingUTF8ThreeDSecureMessageId: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__Xml_Content(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__Xml_Content"), anchor, flags);
	}
	
	

	protected Payment_SubmitHelper()
	{
		setScriptName("Motor_MK2.Payment_Submit");
	}
	
}

