// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Motor_MK2.Done;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Instalments</b><br>
 * Generated     : <b>2015/08/27 12:48:02</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  August 27, 2015
 * @author horned
 */
public abstract class InstalmentsHelper extends Utilities.AA_SuperHelper
{
	/**
	 * RegisterNowsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Register now
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : Submit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_registerNowsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_registerNowsubmit"));
	}
	/**
	 * RegisterNowsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Register now
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : Submit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_registerNowsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_registerNowsubmit"), anchor, flags);
	}
	
	/**
	 * CarInsuranceThankYouForBuyingAACarInsuranceTheAA: with default state.
	 *		.title : RegularExpression(Thank you for buying)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(sale-confirmation)
	 */
	protected DocumentTestObject document_carInsuranceThankYouF() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_carInsuranceThankYouF"));
	}
	/**
	 * CarInsuranceThankYouForBuyingAACarInsuranceTheAA: with specific test context and state.
	 *		.title : RegularExpression(Thank you for buying)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(sale-confirmation)
	 */
	protected DocumentTestObject document_carInsuranceThankYouF(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_carInsuranceThankYouF"), anchor, flags);
	}
	
	/**
	 * main: with default state.
	 *		.id : main
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_main() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_main"));
	}
	/**
	 * main: with specific test context and state.
	 *		.id : main
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_main(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_main"), anchor, flags);
	}
	
	/**
	 * policy_number_holder: with default state.
	 *		.id : policy_number_holder
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_policy_number_holder() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_policy_number_holder"));
	}
	/**
	 * policy_number_holder: with specific test context and state.
	 *		.id : policy_number_holder
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_policy_number_holder(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_policy_number_holder"), anchor, flags);
	}
	
	/**
	 * refPolicyNumber: with default state.
	 *		.id : refPolicyNumber
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_refPolicyNumber() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_refPolicyNumber"));
	}
	/**
	 * refPolicyNumber: with specific test context and state.
	 *		.id : refPolicyNumber
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_refPolicyNumber(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_refPolicyNumber"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"), anchor, flags);
	}
	
	

	protected InstalmentsHelper()
	{
		setScriptName("Motor_MK2.Done.Instalments");
	}
	
}

