// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Travel;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Select_Your_Cover</b><br>
 * Generated     : <b>2014/01/14 11:39:04</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  January 14, 2014
 * @author courtl
 */
public abstract class Select_Your_CoverHelper extends RationalTestScript
{
	/**
	 * aaTiDestination: with default state.
	 *		.text : Please select Europe Worldwide Worldwide exc USA,Canada,Caribbean
	 * 		.id : destination
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.destination
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject Destination() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("Destination"));
	}
	/**
	 * aaTiDestination: with specific test context and state.
	 *		.text : Please select Europe Worldwide Worldwide exc USA,Canada,Caribbean
	 * 		.id : destination
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.destination
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject Destination(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("Destination"), anchor, flags);
	}
	
	/**
	 * aaTiEndDate: with default state.
	 *		.id : return-date
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.endDate
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject End_Date() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("End_Date"));
	}
	/**
	 * aaTiEndDate: with specific test context and state.
	 *		.id : return-date
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.endDate
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject End_Date(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("End_Date"), anchor, flags);
	}
	
	/**
	 * aaTiEndDate: with default state.
	 *		.id : return-date
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.endDate
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject Go_EndDate() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Go_EndDate"));
	}
	/**
	 * aaTiEndDate: with specific test context and state.
	 *		.id : return-date
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.endDate
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject Go_EndDate(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Go_EndDate"), anchor, flags);
	}
	
	/**
	 * aaTiFrontEndSchemeTypePolicyId: with default state.
	 *		.text : RegularExpression(.*)
	 * 		.id : policy-type
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.frontEndSchemeType.policyId
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject Go_Policy_Type() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("Go_Policy_Type"));
	}
	/**
	 * aaTiFrontEndSchemeTypePolicyId: with specific test context and state.
	 *		.text : RegularExpression(.*)
	 * 		.id : policy-type
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.frontEndSchemeType.policyId
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject Go_Policy_Type(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("Go_Policy_Type"), anchor, flags);
	}
	
	/**
	 * aaTiStartDate: with default state.
	 *		.id : departure-date
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.startDate
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject Go_StartDate() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Go_StartDate"));
	}
	/**
	 * aaTiStartDate: with specific test context and state.
	 *		.id : departure-date
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.startDate
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject Go_StartDate(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Go_StartDate"), anchor, flags);
	}
	
	/**
	 * aaTiFrontEndSchemeTypePolicyId: with default state.
	 *		.text : Single Trip Annual Annual (inc Winter Sports) Backpackers Golf Wedding Winter Sp ...
	 * 		.id : policy-type
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.frontEndSchemeType.policyId
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject Policy_Type() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("Policy_Type"));
	}
	/**
	 * aaTiFrontEndSchemeTypePolicyId: with specific test context and state.
	 *		.text : Single Trip Annual Annual (inc Winter Sports) Backpackers Golf Wedding Winter Sp ...
	 * 		.id : policy-type
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.frontEndSchemeType.policyId
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject Policy_Type(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("Policy_Type"), anchor, flags);
	}
	
	/**
	 * aaTiFrontEndSchemeTypePolicyId: with default state.
	 *		.text : Single Trip Annual Annual (inc Winter Sports) Backpackers Golf Wedding Winter Sp ...
	 * 		.id : policy-type
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.frontEndSchemeType.policyId
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject Policy_Type_old() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("Policy_Type_old"));
	}
	/**
	 * aaTiFrontEndSchemeTypePolicyId: with specific test context and state.
	 *		.text : Single Trip Annual Annual (inc Winter Sports) Backpackers Golf Wedding Winter Sp ...
	 * 		.id : policy-type
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.frontEndSchemeType.policyId
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject Policy_Type_old(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("Policy_Type_old"), anchor, flags);
	}
	
	/**
	 * aaTiStartDate: with default state.
	 *		.id : departure-date
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.startDate
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject Start_Date() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Start_Date"));
	}
	/**
	 * aaTiStartDate: with specific test context and state.
	 *		.id : departure-date
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.startDate
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject Start_Date(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("Start_Date"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Continuesubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : RegularExpression(.*)
	 * 		.title : RegularExpression(.*)
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_continuesubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_continuesubmit"));
	}
	/**
	 * Continuesubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : RegularExpression(.*)
	 * 		.title : RegularExpression(.*)
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_continuesubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_continuesubmit"), anchor, flags);
	}
	
	/**
	 * YourQuotesubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : RegularExpression(Your [Qq]uote)
	 * 		.title : RegularExpression(Your [Qq]uote)
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_yourQuotesubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yourQuotesubmit"));
	}
	/**
	 * YourQuotesubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : RegularExpression(Your [Qq]uote)
	 * 		.title : RegularExpression(Your [Qq]uote)
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_yourQuotesubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yourQuotesubmit"), anchor, flags);
	}
	
	/**
	 * AATravelInsurance: with default state.
	 *		.title : RegularExpression(.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(.*)
	 */
	protected DocumentTestObject document_aaTravelInsurance() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_aaTravelInsurance"));
	}
	/**
	 * AATravelInsurance: with specific test context and state.
	 *		.title : RegularExpression(.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(.*)
	 */
	protected DocumentTestObject document_aaTravelInsurance(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_aaTravelInsurance"), anchor, flags);
	}
	
	/**
	 * AATravelInsurance: with default state.
	 *		.title : RegularExpression(.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(.*)
	 */
	protected DocumentTestObject document_aaTravelInsurance2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_aaTravelInsurance2"));
	}
	/**
	 * AATravelInsurance: with specific test context and state.
	 *		.title : RegularExpression(.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(.*)
	 */
	protected DocumentTestObject document_aaTravelInsurance2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_aaTravelInsurance2"), anchor, flags);
	}
	
	/**
	 * destinationTypeDiv: with default state.
	 *		.id : destination-type-div
	 * 		.title : 
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_destinationTypeDiv() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_destinationTypeDiv"));
	}
	/**
	 * destinationTypeDiv: with specific test context and state.
	 *		.id : destination-type-div
	 * 		.title : 
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_destinationTypeDiv(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_destinationTypeDiv"), anchor, flags);
	}
	
	/**
	 * divContentLeft: with default state.
	 *		.id : div-content-left
	 * 		.title : 
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_divContentLeft() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divContentLeft"));
	}
	/**
	 * divContentLeft: with specific test context and state.
	 *		.id : div-content-left
	 * 		.title : 
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_divContentLeft(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divContentLeft"), anchor, flags);
	}
	
	/**
	 * divHomepageProducts: with default state.
	 *		.id : div-homepage-products
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 4
	 */
	protected GuiTestObject html_divHomepageProducts() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divHomepageProducts"));
	}
	/**
	 * divHomepageProducts: with specific test context and state.
	 *		.id : div-homepage-products
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 4
	 */
	protected GuiTestObject html_divHomepageProducts(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divHomepageProducts"), anchor, flags);
	}
	
	/**
	 * divHomepageProducts: with default state.
	 *		.id : div-homepage-products
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_divHomepageProducts2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divHomepageProducts2"));
	}
	/**
	 * divHomepageProducts: with specific test context and state.
	 *		.id : div-homepage-products
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_divHomepageProducts2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divHomepageProducts2"), anchor, flags);
	}
	
	/**
	 * divOuter: with default state.
	 *		.id : div-outer
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_divOuter() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divOuter"));
	}
	/**
	 * divOuter: with specific test context and state.
	 *		.id : div-outer
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_divOuter(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divOuter"), anchor, flags);
	}
	
	/**
	 * divPageImage: with default state.
	 *		.id : div-page-image
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_divPageImage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divPageImage"));
	}
	/**
	 * divPageImage: with specific test context and state.
	 *		.id : div-page-image
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_divPageImage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divPageImage"), anchor, flags);
	}
	
	/**
	 * divQuoteSummary: with default state.
	 *		.id : div-quote-summary
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : NR:Range[0 .. 1]
	 */
	protected GuiTestObject html_divQuoteSummary() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divQuoteSummary"));
	}
	/**
	 * divQuoteSummary: with specific test context and state.
	 *		.id : div-quote-summary
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : NR:Range[0 .. 1]
	 */
	protected GuiTestObject html_divQuoteSummary(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_divQuoteSummary"), anchor, flags);
	}
	
	/**
	 * GetAQuote: with default state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote"));
	}
	/**
	 * GetAQuote: with specific test context and state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote"), anchor, flags);
	}
	
	/**
	 * GetAQuote: with default state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote2"));
	}
	/**
	 * GetAQuote: with specific test context and state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote2"), anchor, flags);
	}
	
	/**
	 * GetAQuote: with default state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote3() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote3"));
	}
	/**
	 * GetAQuote: with specific test context and state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote3(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote3"), anchor, flags);
	}
	
	/**
	 * GetAQuote: with default state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.1stoptravelinsurance.co.uk/images/onestop/btn-get-quote.jpg
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote4() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote4"));
	}
	/**
	 * GetAQuote: with specific test context and state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.1stoptravelinsurance.co.uk/images/onestop/btn-get-quote.jpg
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote4(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote4"), anchor, flags);
	}
	
	/**
	 * GetAQuote: with default state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.1stoptravelinsurance.co.uk/images/onestop/btn-quote.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote5() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote5"));
	}
	/**
	 * GetAQuote: with specific test context and state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.1stoptravelinsurance.co.uk/images/onestop/btn-quote.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote5(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote5"), anchor, flags);
	}
	
	/**
	 * GetAQuote: with default state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.1stoptravelinsurance.co.uk/images/onestop/btn-get-quote.jpg
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote6() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote6"));
	}
	/**
	 * GetAQuote: with specific test context and state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.1stoptravelinsurance.co.uk/images/onestop/btn-get-quote.jpg
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote6(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote6"), anchor, flags);
	}
	
	/**
	 * GetAQuote: with default state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : RegularExpression(http.*1stoptravelinsurance\.co\.uk/images/onestop/btn-quote\.p ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote7() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote7"));
	}
	/**
	 * GetAQuote: with specific test context and state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : RegularExpression(http.*1stoptravelinsurance\.co\.uk/images/onestop/btn-quote\.p ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote7(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote7"), anchor, flags);
	}
	
	/**
	 * GetAQuote: with default state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.1stoptravelinsurance.co.uk/images/onestop/btn-get-quote.jpg
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote8() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote8"));
	}
	/**
	 * GetAQuote: with specific test context and state.
	 *		.alt : Get a quote
	 * 		.id : 
	 * 		.src : http://www.1stoptravelinsurance.co.uk/images/onestop/btn-get-quote.jpg
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getAQuote8(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getAQuote8"), anchor, flags);
	}
	
	/**
	 * GetATravelInsuranceQuote: with default state.
	 *		.alt : Get a travel insurance quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getATravelInsuranceQuote() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getATravelInsuranceQuote"));
	}
	/**
	 * GetATravelInsuranceQuote: with specific test context and state.
	 *		.alt : Get a travel insurance quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getATravelInsuranceQuote(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getATravelInsuranceQuote"), anchor, flags);
	}
	
	/**
	 * GetATravelInsuranceQuote: with default state.
	 *		.alt : Get a travel insurance quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getATravelInsuranceQuote2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getATravelInsuranceQuote2"));
	}
	/**
	 * GetATravelInsuranceQuote: with specific test context and state.
	 *		.alt : Get a travel insurance quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getATravelInsuranceQuote2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getATravelInsuranceQuote2"), anchor, flags);
	}
	
	/**
	 * GetATravelInsuranceQuote: with default state.
	 *		.alt : Get a travel insurance quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getATravelInsuranceQuote3() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getATravelInsuranceQuote3"));
	}
	/**
	 * GetATravelInsuranceQuote: with specific test context and state.
	 *		.alt : Get a travel insurance quote
	 * 		.id : 
	 * 		.src : http://www.gotravelinsurance.co.uk/images/go/btn-get-a-quote.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_getATravelInsuranceQuote3(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_getATravelInsuranceQuote3"), anchor, flags);
	}
	
	/**
	 * aaTiTravelCustomers0Title: with default state.
	 *		.text : Please select Mr Mrs Miss Ms Dr
	 * 		.id : title
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.travelCustomers[0].title
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_Lead_Customer_Title() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_Lead_Customer_Title"));
	}
	/**
	 * aaTiTravelCustomers0Title: with specific test context and state.
	 *		.text : Please select Mr Mrs Miss Ms Dr
	 * 		.id : title
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.travelCustomers[0].title
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_Lead_Customer_Title(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_Lead_Customer_Title"), anchor, flags);
	}
	
	/**
	 * aaTiDestination: with default state.
	 *		.text : Please select Australia & New Zealand Europe UK/Channel Islands/Ireland Worldwid ...
	 * 		.id : destination
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.destination
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_aaTiDestination() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaTiDestination"));
	}
	/**
	 * aaTiDestination: with specific test context and state.
	 *		.text : Please select Australia & New Zealand Europe UK/Channel Islands/Ireland Worldwid ...
	 * 		.id : destination
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.destination
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_aaTiDestination(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaTiDestination"), anchor, flags);
	}
	
	/**
	 * aaTiTravellergroup: with default state.
	 *		.text : Please select Individual Couple Family
	 * 		.id : travellergroup
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_aaTiTravellergroup() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaTiTravellergroup"));
	}
	/**
	 * aaTiTravellergroup: with specific test context and state.
	 *		.text : Please select Individual Couple Family
	 * 		.id : travellergroup
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_aaTiTravellergroup(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaTiTravellergroup"), anchor, flags);
	}
	
	/**
	 * aaTiTravellergroupCOUPLE: with default state.
	 *		.id : aa.ti.travellergroup2
	 * 		.type : radio
	 * 		.value : COUPLE
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_Couple() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_Couple"));
	}
	/**
	 * aaTiTravellergroupCOUPLE: with specific test context and state.
	 *		.id : aa.ti.travellergroup2
	 * 		.type : radio
	 * 		.value : COUPLE
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_Couple(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_Couple"), anchor, flags);
	}
	
	/**
	 * aaTiDestinationTypefalse: with default state.
	 *		.id : destination-many
	 * 		.type : radio
	 * 		.value : false
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.destination-type
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_DestinationType() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_DestinationType"));
	}
	/**
	 * aaTiDestinationTypefalse: with specific test context and state.
	 *		.id : destination-many
	 * 		.type : radio
	 * 		.value : false
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.destination-type
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_DestinationType(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_DestinationType"), anchor, flags);
	}
	
	/**
	 * aaTiTravellergroupFAMILY: with default state.
	 *		.id : aa.ti.travellergroup3
	 * 		.type : radio
	 * 		.value : FAMILY
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 2
	 */
	protected ToggleGUITestObject radioButton_Family() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_Family"));
	}
	/**
	 * aaTiTravellergroupFAMILY: with specific test context and state.
	 *		.id : aa.ti.travellergroup3
	 * 		.type : radio
	 * 		.value : FAMILY
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 2
	 */
	protected ToggleGUITestObject radioButton_Family(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_Family"), anchor, flags);
	}
	
	/**
	 * aaTiTravellergroupINDIVIDUAL_S: with default state.
	 *		.id : aa.ti.travellergroup1
	 * 		.type : radio
	 * 		.value : INDIVIDUAL_S
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_Individual() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_Individual"));
	}
	/**
	 * aaTiTravellergroupINDIVIDUAL_S: with specific test context and state.
	 *		.id : aa.ti.travellergroup1
	 * 		.type : radio
	 * 		.value : INDIVIDUAL_S
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_Individual(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_Individual"), anchor, flags);
	}
	
	/**
	 * aaTiTravellergroupINDIVIDUAL_S: with default state.
	 *		.id : aa.ti.travellergroup1
	 * 		.type : radio
	 * 		.value : INDIVIDUAL_S
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_aaTiTravellergroup() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_aaTiTravellergroup"));
	}
	/**
	 * aaTiTravellergroupINDIVIDUAL_S: with specific test context and state.
	 *		.id : aa.ti.travellergroup1
	 * 		.type : radio
	 * 		.value : INDIVIDUAL_S
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_aaTiTravellergroup(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_aaTiTravellergroup"), anchor, flags);
	}
	
	/**
	 * aaTiTravellergroupCOUPLE: with default state.
	 *		.id : aa.ti.travellergroup2
	 * 		.type : radio
	 * 		.value : COUPLE
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_aaTiTravellergroup2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_aaTiTravellergroup2"));
	}
	/**
	 * aaTiTravellergroupCOUPLE: with specific test context and state.
	 *		.id : aa.ti.travellergroup2
	 * 		.type : radio
	 * 		.value : COUPLE
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_aaTiTravellergroup2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_aaTiTravellergroup2"), anchor, flags);
	}
	
	/**
	 * aaTiTravellergroupFAMILY: with default state.
	 *		.id : aa.ti.travellergroup3
	 * 		.type : radio
	 * 		.value : FAMILY
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 2
	 */
	protected ToggleGUITestObject radioButton_aaTiTravellergroup3() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_aaTiTravellergroup3"));
	}
	/**
	 * aaTiTravellergroupFAMILY: with specific test context and state.
	 *		.id : aa.ti.travellergroup3
	 * 		.type : radio
	 * 		.value : FAMILY
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.ti.travellergroup
	 * 		.classIndex : 2
	 */
	protected ToggleGUITestObject radioButton_aaTiTravellergroup3(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_aaTiTravellergroup3"), anchor, flags);
	}
	
	/**
	 * aaTiTravelCustomers0LastName: with default state.
	 *		.id : traveller_1_last_name
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.travelCustomers[0].lastName
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject textLead_Customer_Lastname() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("textLead_Customer_Lastname"));
	}
	/**
	 * aaTiTravelCustomers0LastName: with specific test context and state.
	 *		.id : traveller_1_last_name
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.travelCustomers[0].lastName
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject textLead_Customer_Lastname(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("textLead_Customer_Lastname"), anchor, flags);
	}
	
	/**
	 * aaTiContactnumberNumber: with default state.
	 *		.id : telephone
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.contactnumber.number
	 * 		.classIndex : 3
	 */
	protected TextGuiTestObject text_Lead_Customer_Contact_Number() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_Lead_Customer_Contact_Number"));
	}
	/**
	 * aaTiContactnumberNumber: with specific test context and state.
	 *		.id : telephone
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.contactnumber.number
	 * 		.classIndex : 3
	 */
	protected TextGuiTestObject text_Lead_Customer_Contact_Number(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_Lead_Customer_Contact_Number"), anchor, flags);
	}
	
	/**
	 * aaTiTravelCustomers0Dob: with default state.
	 *		.id : traveller_0_age
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.leadTraveller.dob
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_Lead_Customer_DOB() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_Lead_Customer_DOB"));
	}
	/**
	 * aaTiTravelCustomers0Dob: with specific test context and state.
	 *		.id : traveller_0_age
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.leadTraveller.dob
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_Lead_Customer_DOB(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_Lead_Customer_DOB"), anchor, flags);
	}
	
	/**
	 * aaTiEmail: with default state.
	 *		.id : email
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.email
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_Lead_Customer_Email() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_Lead_Customer_Email"));
	}
	/**
	 * aaTiEmail: with specific test context and state.
	 *		.id : email
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.email
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_Lead_Customer_Email(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_Lead_Customer_Email"), anchor, flags);
	}
	
	/**
	 * aaTiTravelCustomers0FirstName: with default state.
	 *		.id : traveller_1_first_name
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.travelCustomers[0].firstName
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_Lead_Customer_Firstname() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_Lead_Customer_Firstname"));
	}
	/**
	 * aaTiTravelCustomers0FirstName: with specific test context and state.
	 *		.id : traveller_1_first_name
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.travelCustomers[0].firstName
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_Lead_Customer_Firstname(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_Lead_Customer_Firstname"), anchor, flags);
	}
	
	/**
	 * aaTiContactnumberMobileNumber: with default state.
	 *		.id : mobile
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.contactnumber.mobileNumber
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_aaTiContactnumberMobileNu() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_aaTiContactnumberMobileNu"));
	}
	/**
	 * aaTiContactnumberMobileNumber: with specific test context and state.
	 *		.id : mobile
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.contactnumber.mobileNumber
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_aaTiContactnumberMobileNu(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_aaTiContactnumberMobileNu"), anchor, flags);
	}
	
	/**
	 * aaTiLeadTravellerDob: with default state.
	 *		.id : traveller_0_age
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.leadTraveller.dob
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_aaTiLeadTravellerDob() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_aaTiLeadTravellerDob"));
	}
	/**
	 * aaTiLeadTravellerDob: with specific test context and state.
	 *		.id : traveller_0_age
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.ti.leadTraveller.dob
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_aaTiLeadTravellerDob(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_aaTiLeadTravellerDob"), anchor, flags);
	}
	
	

	protected Select_Your_CoverHelper()
	{
		setScriptName("Travel.Select_Your_Cover");
	}
	
}

