// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.BreakDown_Cover_MK2.Variations;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Add_Family</b><br>
 * Generated     : <b>2015/06/10 15:00:42</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  June 10, 2015
 * @author horned
 */
public abstract class Add_FamilyHelper extends Utilities.AA_SuperHelper
{
	/**
	 * BreakdownCoverYourDetailsAA: with default state.
	 *		.title : RegularExpression(Cover)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(cover)
	 */
	protected DocumentTestObject document_breakdownCoverYourDet() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_breakdownCoverYourDet"));
	}
	/**
	 * BreakdownCoverYourDetailsAA: with specific test context and state.
	 *		.title : RegularExpression(Cover)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(cover)
	 */
	protected DocumentTestObject document_breakdownCoverYourDet(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_breakdownCoverYourDet"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"), anchor, flags);
	}
	
	/**
	 * Miss: with default state.
	 *		.id : 
	 * 		.value : Miss
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 25
	 */
	protected GuiTestObject label_miss3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_miss3"));
	}
	/**
	 * Miss: with specific test context and state.
	 *		.id : 
	 * 		.value : Miss
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 25
	 */
	protected GuiTestObject label_miss3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_miss3"), anchor, flags);
	}
	
	/**
	 * Miss: with default state.
	 *		.id : 
	 * 		.value : Miss
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 32
	 */
	protected GuiTestObject label_miss4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_miss4"));
	}
	/**
	 * Miss: with specific test context and state.
	 *		.id : 
	 * 		.value : Miss
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 32
	 */
	protected GuiTestObject label_miss4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_miss4"), anchor, flags);
	}
	
	/**
	 * Mr: with default state.
	 *		.id : 
	 * 		.value : Mr
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 23
	 */
	protected GuiTestObject label_mr3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mr3"));
	}
	/**
	 * Mr: with specific test context and state.
	 *		.id : 
	 * 		.value : Mr
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 23
	 */
	protected GuiTestObject label_mr3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mr3"), anchor, flags);
	}
	
	/**
	 * Mr: with default state.
	 *		.id : 
	 * 		.value : Mr
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 30
	 */
	protected GuiTestObject label_mr4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mr4"));
	}
	/**
	 * Mr: with specific test context and state.
	 *		.id : 
	 * 		.value : Mr
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 30
	 */
	protected GuiTestObject label_mr4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mr4"), anchor, flags);
	}
	
	/**
	 * Mrs: with default state.
	 *		.id : 
	 * 		.value : Mrs
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 24
	 */
	protected GuiTestObject label_mrs3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mrs3"));
	}
	/**
	 * Mrs: with specific test context and state.
	 *		.id : 
	 * 		.value : Mrs
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 24
	 */
	protected GuiTestObject label_mrs3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mrs3"), anchor, flags);
	}
	
	/**
	 * Mrs: with default state.
	 *		.id : 
	 * 		.value : Mrs
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 31
	 */
	protected GuiTestObject label_mrs4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mrs4"));
	}
	/**
	 * Mrs: with specific test context and state.
	 *		.id : 
	 * 		.value : Mrs
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 31
	 */
	protected GuiTestObject label_mrs4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mrs4"), anchor, flags);
	}
	
	/**
	 * Ms: with default state.
	 *		.id : 
	 * 		.value : Ms
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 26
	 */
	protected GuiTestObject label_ms3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_ms3"));
	}
	/**
	 * Ms: with specific test context and state.
	 *		.id : 
	 * 		.value : Ms
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 26
	 */
	protected GuiTestObject label_ms3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_ms3"), anchor, flags);
	}
	
	/**
	 * Ms: with default state.
	 *		.id : 
	 * 		.value : Ms
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 33
	 */
	protected GuiTestObject label_ms4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_ms4"));
	}
	/**
	 * Ms: with specific test context and state.
	 *		.id : 
	 * 		.value : Ms
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 33
	 */
	protected GuiTestObject label_ms4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_ms4"), anchor, flags);
	}
	
	/**
	 * additionalMembers1DateOfBirthDate: with default state.
	 *		.id : policyHolder3Dob
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[1].dateOfBirth.date
	 * 		.classIndex : 14
	 */
	protected TextGuiTestObject text_additionalMembers_3_DOB() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_3_DOB"));
	}
	/**
	 * additionalMembers1DateOfBirthDate: with specific test context and state.
	 *		.id : policyHolder3Dob
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[1].dateOfBirth.date
	 * 		.classIndex : 14
	 */
	protected TextGuiTestObject text_additionalMembers_3_DOB(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_3_DOB"), anchor, flags);
	}
	
	/**
	 * additionalMembers1FirstName: with default state.
	 *		.id : family2Firstname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[1].firstName
	 * 		.classIndex : 12
	 */
	protected TextGuiTestObject text_additionalMembers_3_First() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_3_First"));
	}
	/**
	 * additionalMembers1FirstName: with specific test context and state.
	 *		.id : family2Firstname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[1].firstName
	 * 		.classIndex : 12
	 */
	protected TextGuiTestObject text_additionalMembers_3_First(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_3_First"), anchor, flags);
	}
	
	/**
	 * additionalMembers1Surname: with default state.
	 *		.id : family2Surname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[1].surname
	 * 		.classIndex : 13
	 */
	protected TextGuiTestObject text_additionalMembers_3_Surname() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_3_Surname"));
	}
	/**
	 * additionalMembers1Surname: with specific test context and state.
	 *		.id : family2Surname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[1].surname
	 * 		.classIndex : 13
	 */
	protected TextGuiTestObject text_additionalMembers_3_Surname(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_3_Surname"), anchor, flags);
	}
	
	/**
	 * additionalMembers2DateOfBirthDate: with default state.
	 *		.id : policyHolder4Dob
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[2].dateOfBirth.date
	 * 		.classIndex : 17
	 */
	protected TextGuiTestObject text_additionalMembers_4_DOB() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_4_DOB"));
	}
	/**
	 * additionalMembers2DateOfBirthDate: with specific test context and state.
	 *		.id : policyHolder4Dob
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[2].dateOfBirth.date
	 * 		.classIndex : 17
	 */
	protected TextGuiTestObject text_additionalMembers_4_DOB(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_4_DOB"), anchor, flags);
	}
	
	/**
	 * additionalMembers2FirstName: with default state.
	 *		.id : family3Firstname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[2].firstName
	 * 		.classIndex : 15
	 */
	protected TextGuiTestObject text_additionalMembers_4_First() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_4_First"));
	}
	/**
	 * additionalMembers2FirstName: with specific test context and state.
	 *		.id : family3Firstname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[2].firstName
	 * 		.classIndex : 15
	 */
	protected TextGuiTestObject text_additionalMembers_4_First(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_4_First"), anchor, flags);
	}
	
	/**
	 * additionalMembers2Surname: with default state.
	 *		.id : family3Surname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[2].surname
	 * 		.classIndex : 16
	 */
	protected TextGuiTestObject text_additionalMembers_4_Surname() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_4_Surname"));
	}
	/**
	 * additionalMembers2Surname: with specific test context and state.
	 *		.id : family3Surname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : additionalMembers[2].surname
	 * 		.classIndex : 16
	 */
	protected TextGuiTestObject text_additionalMembers_4_Surname(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_additionalMembers_4_Surname"), anchor, flags);
	}
	
	

	protected Add_FamilyHelper()
	{
		setScriptName("BreakDown_Cover_MK2.Variations.Add_Family");
	}
	
}

