// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.EBC;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Your_Direct_Debit</b><br>
 * Generated     : <b>2013/04/16 14:47:55</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  April 16, 2013
 * @author courtl
 */
public abstract class Your_Direct_DebitHelper extends RationalTestScript
{
	/**
	 * confirmBank: with default state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.class : Html.INPUT.image
	 * 		.title : 
	 * 		.name : confirmBankDetails
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmBank() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmBank"));
	}
	/**
	 * confirmBank: with specific test context and state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.class : Html.INPUT.image
	 * 		.title : 
	 * 		.name : confirmBankDetails
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmBank(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmBank"), anchor, flags);
	}
	
	/**
	 * SubmitDirectDebitDetails: with default state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.class : Html.INPUT.image
	 * 		.title : 
	 * 		.name : submitDirectDebit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_submitDirectDebitDetail() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_submitDirectDebitDetail"));
	}
	/**
	 * SubmitDirectDebitDetails: with specific test context and state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.class : Html.INPUT.image
	 * 		.title : 
	 * 		.name : submitDirectDebit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_submitDirectDebitDetail(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_submitDirectDebitDetail"), anchor, flags);
	}
	
	/**
	 * ebcContent: with default state.
	 *		.id : ebcContent
	 * 		.class : Html.DIV
	 * 		.title : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_ebcContent() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_ebcContent"));
	}
	/**
	 * ebcContent: with specific test context and state.
	 *		.id : ebcContent
	 * 		.class : Html.DIV
	 * 		.title : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_ebcContent(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_ebcContent"), anchor, flags);
	}
	
	/**
	 * accountName: with default state.
	 *		.id : accountName
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : accountName
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_accountName() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_accountName"));
	}
	/**
	 * accountName: with specific test context and state.
	 *		.id : accountName
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : accountName
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_accountName(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_accountName"), anchor, flags);
	}
	
	/**
	 * accountNumber: with default state.
	 *		.id : accountNumber
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : accountNumber
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_accountNumber() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_accountNumber"));
	}
	/**
	 * accountNumber: with specific test context and state.
	 *		.id : accountNumber
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : accountNumber
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_accountNumber(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_accountNumber"), anchor, flags);
	}
	
	/**
	 * sortcode1: with default state.
	 *		.id : sortcode1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : sortcode1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_sortcode1() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_sortcode1"));
	}
	/**
	 * sortcode1: with specific test context and state.
	 *		.id : sortcode1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : sortcode1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_sortcode1(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_sortcode1"), anchor, flags);
	}
	
	/**
	 * sortcode2: with default state.
	 *		.id : sortcode2
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : sortcode2
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_sortcode2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_sortcode2"));
	}
	/**
	 * sortcode2: with specific test context and state.
	 *		.id : sortcode2
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : sortcode2
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_sortcode2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_sortcode2"), anchor, flags);
	}
	
	/**
	 * sortcode3: with default state.
	 *		.id : sortcode3
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : sortcode3
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_sortcode3() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_sortcode3"));
	}
	/**
	 * sortcode3: with specific test context and state.
	 *		.id : sortcode3
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : sortcode3
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_sortcode3(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_sortcode3"), anchor, flags);
	}
	
	

	protected Your_Direct_DebitHelper()
	{
		setScriptName("EBC.Your_Direct_Debit");
	}
	
}

