// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.EBC;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Your_Card_Payment</b><br>
 * Generated     : <b>2013/04/16 14:29:17</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  April 16, 2013
 * @author courtl
 */
public abstract class Your_Card_PaymentHelper extends RationalTestScript
{
	/**
	 * confirmPayment: with default state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.class : Html.INPUT.image
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmPayment() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmPayment"));
	}
	/**
	 * confirmPayment: with specific test context and state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.class : Html.INPUT.image
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmPayment(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmPayment"), anchor, flags);
	}
	
	/**
	 * next: with default state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.class : Html.INPUT.image
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_next() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_next"));
	}
	/**
	 * next: with specific test context and state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.class : Html.INPUT.image
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_next(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_next"), anchor, flags);
	}
	
	/**
	 * pas_ccmonth: with default state.
	 *		.text : 01-Jan 02-Feb 03-Mar 04-Apr 05-May 06-Jun 07-Jul 08-Aug 09-Sep 10-Oct 11-Nov 12- ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : pas_ccmonth
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_pas_ccmonth() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_pas_ccmonth"));
	}
	/**
	 * pas_ccmonth: with specific test context and state.
	 *		.text : 01-Jan 02-Feb 03-Mar 04-Apr 05-May 06-Jun 07-Jul 08-Aug 09-Sep 10-Oct 11-Nov 12- ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : pas_ccmonth
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_pas_ccmonth(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_pas_ccmonth"), anchor, flags);
	}
	
	/**
	 * pas_cctype: with default state.
	 *		.text : Select MasterCard Visa UK Maestro
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : pas_cctype
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_pas_cctype() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_pas_cctype"));
	}
	/**
	 * pas_cctype: with specific test context and state.
	 *		.text : Select MasterCard Visa UK Maestro
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : pas_cctype
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_pas_cctype(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_pas_cctype"), anchor, flags);
	}
	
	/**
	 * pas_ccyear: with default state.
	 *		.text : 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : pas_ccyear
	 * 		.classIndex : 2
	 */
	protected SelectGuiSubitemTestObject list_pas_ccyear() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_pas_ccyear"));
	}
	/**
	 * pas_ccyear: with specific test context and state.
	 *		.text : 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : pas_ccyear
	 * 		.classIndex : 2
	 */
	protected SelectGuiSubitemTestObject list_pas_ccyear(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_pas_ccyear"), anchor, flags);
	}
	
	/**
	 * pas_cccvc: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : pas_cccvc
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_pas_cccvc() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pas_cccvc"));
	}
	/**
	 * pas_cccvc: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : pas_cccvc
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_pas_cccvc(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pas_cccvc"), anchor, flags);
	}
	
	/**
	 * pas_ccname: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : pas_ccname
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_pas_ccname() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pas_ccname"));
	}
	/**
	 * pas_ccname: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : pas_ccname
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_pas_ccname(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pas_ccname"), anchor, flags);
	}
	
	/**
	 * pas_ccnum: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : pas_ccnum
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_pas_ccnum() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pas_ccnum"));
	}
	/**
	 * pas_ccnum: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : pas_ccnum
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_pas_ccnum(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pas_ccnum"), anchor, flags);
	}
	
	

	protected Your_Card_PaymentHelper()
	{
		setScriptName("EBC.Your_Card_Payment");
	}
	
}

