// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Road;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Your_CMM</b><br>
 * Generated     : <b>2014/08/13 14:38:37</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  August 13, 2014
 * @author courtl
 */
public abstract class Your_CMMHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * BuyBreakdownCoverbutton: with default state.
	 *		.id : submitToPCI
	 * 		.type : button
	 * 		.value : Buy breakdown cover
	 * 		.class : Html.INPUT.button
	 * 		.title : 
	 * 		.name : submitAppForm
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buyBreakdownCoverbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyBreakdownCoverbutton"));
	}
	/**
	 * BuyBreakdownCoverbutton: with specific test context and state.
	 *		.id : submitToPCI
	 * 		.type : button
	 * 		.value : Buy breakdown cover
	 * 		.class : Html.INPUT.button
	 * 		.title : 
	 * 		.name : submitAppForm
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buyBreakdownCoverbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyBreakdownCoverbutton"), anchor, flags);
	}
	
	/**
	 * BuyNowsubmit: with default state.
	 *		.id : card-detail-button
	 * 		.type : submit
	 * 		.value : Next
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buyNowsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNowsubmit"));
	}
	/**
	 * BuyNowsubmit: with specific test context and state.
	 *		.id : card-detail-button
	 * 		.type : submit
	 * 		.value : Next
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buyNowsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNowsubmit"), anchor, flags);
	}
	
	/**
	 * submit: with default state.
	 *		.id : submitAppForm
	 * 		.type : image
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.image
	 * 		.name : submitAppForm
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_submit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_submit"));
	}
	/**
	 * submit: with specific test context and state.
	 *		.id : submitAppForm
	 * 		.type : image
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.image
	 * 		.name : submitAppForm
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_submit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_submit"), anchor, flags);
	}
	
	/**
	 * terms_Conditiontrue: with default state.
	 *		.id : terms_Condition
	 * 		.type : checkbox
	 * 		.value : true
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : terms_Condition
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_terms_Conditiontrue() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_terms_Conditiontrue"));
	}
	/**
	 * terms_Conditiontrue: with specific test context and state.
	 *		.id : terms_Condition
	 * 		.type : checkbox
	 * 		.value : true
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : terms_Condition
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_terms_Conditiontrue(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_terms_Conditiontrue"), anchor, flags);
	}
	
	/**
	 * terms_Conditiontrue: with default state.
	 *		.id : terms_Condition
	 * 		.type : checkbox
	 * 		.value : true
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : terms_Condition
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_terms_Conditiontrue2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_terms_Conditiontrue2"));
	}
	/**
	 * terms_Conditiontrue: with specific test context and state.
	 *		.id : terms_Condition
	 * 		.type : checkbox
	 * 		.value : true
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : terms_Condition
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_terms_Conditiontrue2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_terms_Conditiontrue2"), anchor, flags);
	}
	
	/**
	 * BreakdownCoverYourPaymentTheAA: with default state.
	 *		.title : Breakdown Cover : Your payment - The AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https://.*\.theaa\.com/breakdown-cover/uk-breakdown/submit-cus ...
	 */
	protected DocumentTestObject document_breakdownCoverYourPay() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_breakdownCoverYourPay"));
	}
	/**
	 * BreakdownCoverYourPaymentTheAA: with specific test context and state.
	 *		.title : Breakdown Cover : Your payment - The AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(https://.*\.theaa\.com/breakdown-cover/uk-breakdown/submit-cus ...
	 */
	protected DocumentTestObject document_breakdownCoverYourPay(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_breakdownCoverYourPay"), anchor, flags);
	}
	
	/**
	 * TheAAPaymentGateway: with default state.
	 *		.title : The AA: Payment Gateway
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://uat-payments.theaa.com/01/start
	 */
	protected DocumentTestObject document_theAAPaymentGateway() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_theAAPaymentGateway"));
	}
	/**
	 * TheAAPaymentGateway: with specific test context and state.
	 *		.title : The AA: Payment Gateway
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://uat-payments.theaa.com/01/start
	 */
	protected DocumentTestObject document_theAAPaymentGateway(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_theAAPaymentGateway"), anchor, flags);
	}
	
	/**
	 * bdWrap: with default state.
	 *		.id : bd-wrap
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_bdWrap() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_bdWrap"));
	}
	/**
	 * bdWrap: with specific test context and state.
	 *		.id : bd-wrap
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_bdWrap(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_bdWrap"), anchor, flags);
	}
	
	/**
	 * AACreditCardApplyToday: with default state.
	 *		.alt : AA Credit Card. Apply today
	 * 		.id : 
	 * 		.src : https://prelive5.theaa.com/images/ads/financial-services/credit-card/earnmoney5. ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_aaCreditCardApplyToday() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_aaCreditCardApplyToday"));
	}
	/**
	 * AACreditCardApplyToday: with specific test context and state.
	 *		.alt : AA Credit Card. Apply today
	 * 		.id : 
	 * 		.src : https://prelive5.theaa.com/images/ads/financial-services/credit-card/earnmoney5. ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_aaCreditCardApplyToday(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_aaCreditCardApplyToday"), anchor, flags);
	}
	
	/**
	 * AACreditCardApplyToday: with default state.
	 *		.alt : AA Credit Card. Apply today
	 * 		.id : 
	 * 		.src : https://213.225.132.246/images/ads/financial-services/credit-card/earnmoney5.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_aaCreditCardApplyToday2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_aaCreditCardApplyToday2"));
	}
	/**
	 * AACreditCardApplyToday: with specific test context and state.
	 *		.alt : AA Credit Card. Apply today
	 * 		.id : 
	 * 		.src : https://213.225.132.246/images/ads/financial-services/credit-card/earnmoney5.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_aaCreditCardApplyToday2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_aaCreditCardApplyToday2"), anchor, flags);
	}
	
	/**
	 * submit: with default state.
	 *		.alt : submit
	 * 		.id : 
	 * 		.src : https://prelive7.theaa.com/images/breakdown/journey/continue.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_submit() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_submit"));
	}
	/**
	 * submit: with specific test context and state.
	 *		.alt : submit
	 * 		.id : 
	 * 		.src : https://prelive7.theaa.com/images/breakdown/journey/continue.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_submit(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_submit"), anchor, flags);
	}
	
	/**
	 * CardModelExpiryDateModelMonth: with default state.
	 *		.text : MM 01 02 03 04 05 06 07 08 09 10 11 12
	 * 		.id : CardModel_ExpiryDateModel_Month
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : CardModel.ExpiryDateModel.Month
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_cardModelExpiryDateModelM() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_cardModelExpiryDateModelM"));
	}
	/**
	 * CardModelExpiryDateModelMonth: with specific test context and state.
	 *		.text : MM 01 02 03 04 05 06 07 08 09 10 11 12
	 * 		.id : CardModel_ExpiryDateModel_Month
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : CardModel.ExpiryDateModel.Month
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_cardModelExpiryDateModelM(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_cardModelExpiryDateModelM"), anchor, flags);
	}
	
	/**
	 * CardModelExpiryDateModelYear: with default state.
	 *		.text : YYYY 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024
	 * 		.id : CardModel_ExpiryDateModel_Year
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : CardModel.ExpiryDateModel.Year
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_cardModelExpiryDateModelY() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_cardModelExpiryDateModelY"));
	}
	/**
	 * CardModelExpiryDateModelYear: with specific test context and state.
	 *		.text : YYYY 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024
	 * 		.id : CardModel_ExpiryDateModel_Year
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : CardModel.ExpiryDateModel.Year
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_cardModelExpiryDateModelY(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_cardModelExpiryDateModelY"), anchor, flags);
	}
	
	/**
	 * CardModelTypeModelCodedValue: with default state.
	 *		.text : Select Visa Mastercard AA Visa AA Mastercard Visa Debit Mastercard Debit
	 * 		.id : CardModel_TypeModel_CodedValue
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : CardModel.TypeModel.CodedValue
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_cardModelTypeModelCodedVa() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_cardModelTypeModelCodedVa"));
	}
	/**
	 * CardModelTypeModelCodedValue: with specific test context and state.
	 *		.text : Select Visa Mastercard AA Visa AA Mastercard Visa Debit Mastercard Debit
	 * 		.id : CardModel_TypeModel_CodedValue
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : CardModel.TypeModel.CodedValue
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_cardModelTypeModelCodedVa(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_cardModelTypeModelCodedVa"), anchor, flags);
	}
	
	/**
	 * expiryMonth: with default state.
	 *		.text : MM 01 02 03 04 05 06 07 08 09 10 11 12
	 * 		.id : expiryMonth
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : expiryMonth
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_expiryMonth() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_expiryMonth"));
	}
	/**
	 * expiryMonth: with specific test context and state.
	 *		.text : MM 01 02 03 04 05 06 07 08 09 10 11 12
	 * 		.id : expiryMonth
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : expiryMonth
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_expiryMonth(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_expiryMonth"), anchor, flags);
	}
	
	/**
	 * expiryYear: with default state.
	 *		.text : YYYY 2013 2014 2015 2016 2017 2018 2019
	 * 		.id : expiryYear
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : expiryYear
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_expiryYear() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_expiryYear"));
	}
	/**
	 * expiryYear: with specific test context and state.
	 *		.text : YYYY 2013 2014 2015 2016 2017 2018 2019
	 * 		.id : expiryYear
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : expiryYear
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_expiryYear(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_expiryYear"), anchor, flags);
	}
	
	/**
	 * paymentMethod: with default state.
	 *		.text : Visa Debit Mastercard Debit Visa Credit Mastercard Credit AA Mastercard Credit A ...
	 * 		.id : paymentMethod
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : paymentMethod
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_paymentMethod() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_paymentMethod"));
	}
	/**
	 * paymentMethod: with specific test context and state.
	 *		.text : Visa Debit Mastercard Debit Visa Credit Mastercard Credit AA Mastercard Credit A ...
	 * 		.id : paymentMethod
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : paymentMethod
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_paymentMethod(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_paymentMethod"), anchor, flags);
	}
	
	/**
	 * accountName: with default state.
	 *		.id : accountName
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : accountName
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_accountName() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_accountName"));
	}
	/**
	 * accountName: with specific test context and state.
	 *		.id : accountName
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : accountName
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_accountName(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_accountName"), anchor, flags);
	}
	
	/**
	 * accountNo: with default state.
	 *		.id : accountNo
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : accountNo
	 * 		.classIndex : 3
	 */
	protected TextGuiTestObject text_accountNo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_accountNo"));
	}
	/**
	 * accountNo: with specific test context and state.
	 *		.id : accountNo
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : accountNo
	 * 		.classIndex : 3
	 */
	protected TextGuiTestObject text_accountNo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_accountNo"), anchor, flags);
	}
	
	/**
	 * CardModelAccountNumberModelValue: with default state.
	 *		.id : CardModel_AccountNumberModel_Value
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : CardModel.AccountNumberModel.Value
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cardModelAccountNumberMod() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cardModelAccountNumberMod"));
	}
	/**
	 * CardModelAccountNumberModelValue: with specific test context and state.
	 *		.id : CardModel_AccountNumberModel_Value
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : CardModel.AccountNumberModel.Value
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cardModelAccountNumberMod(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cardModelAccountNumberMod"), anchor, flags);
	}
	
	/**
	 * CardModelCardholderNameModelFullname: with default state.
	 *		.id : CardModel_CardholderNameModel_Fullname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : CardModel.CardholderNameModel.Fullname
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_cardModelCardholderNameMo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cardModelCardholderNameMo"));
	}
	/**
	 * CardModelCardholderNameModelFullname: with specific test context and state.
	 *		.id : CardModel_CardholderNameModel_Fullname
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : CardModel.CardholderNameModel.Fullname
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_cardModelCardholderNameMo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cardModelCardholderNameMo"), anchor, flags);
	}
	
	/**
	 * CardModelVerificationNumberModelValue: with default state.
	 *		.id : CardModel_VerificationNumberModel_Value
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : CardModel.VerificationNumberModel.Value
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_cardModelVerificationNumb() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cardModelVerificationNumb"));
	}
	/**
	 * CardModelVerificationNumberModelValue: with specific test context and state.
	 *		.id : CardModel_VerificationNumberModel_Value
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : CardModel.VerificationNumberModel.Value
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_cardModelVerificationNumb(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cardModelVerificationNumb"), anchor, flags);
	}
	
	/**
	 * cardNo: with default state.
	 *		.id : cardNo
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : cardNo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cardNo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cardNo"));
	}
	/**
	 * cardNo: with specific test context and state.
	 *		.id : cardNo
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : cardNo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cardNo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cardNo"), anchor, flags);
	}
	
	/**
	 * nameOnCard: with default state.
	 *		.id : nameOnCard
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : nameOnCard
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_nameOnCard() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_nameOnCard"));
	}
	/**
	 * nameOnCard: with specific test context and state.
	 *		.id : nameOnCard
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : nameOnCard
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_nameOnCard(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_nameOnCard"), anchor, flags);
	}
	
	/**
	 * sortCode: with default state.
	 *		.id : sort_code_id
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : sortCode
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_sortCode() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_sortCode"));
	}
	/**
	 * sortCode: with specific test context and state.
	 *		.id : sort_code_id
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : sortCode
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_sortCode(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_sortCode"), anchor, flags);
	}
	
	

	protected Your_CMMHelper()
	{
		setScriptName("Road.Your_CMM");
	}
	
}

