// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Motor_MK2.Your__Details;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Motor_Conviction_Details</b><br>
 * Generated     : <b>2015/10/22 13:03:57</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  October 22, 2015
 * @author horned
 */
public abstract class Motor_Conviction_DetailsHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * CarInsuranceYourDetailsTheAA: with default state.
	 *		.title : RegularExpression(Your details)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(car-insurance)
	 */
	protected DocumentTestObject document_carInsuranceYourDetai() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_carInsuranceYourDetai"));
	}
	/**
	 * CarInsuranceYourDetailsTheAA: with specific test context and state.
	 *		.title : RegularExpression(Your details)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(car-insurance)
	 */
	protected DocumentTestObject document_carInsuranceYourDetai(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_carInsuranceYourDetai"), anchor, flags);
	}
	
	/**
	 * No: with default state.
	 *		.id : 
	 * 		.value : No
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		for : motoring-offense-no
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected GuiTestObject label_Convictions_no() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_Convictions_no"));
	}
	/**
	 * No: with specific test context and state.
	 *		.id : 
	 * 		.value : No
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		for : motoring-offense-no
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected GuiTestObject label_Convictions_no(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_Convictions_no"), anchor, flags);
	}
	
	/**
	 * Yes: with default state.
	 *		.id : 
	 * 		.value : Yes
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		for : motoring-offense-yes
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected GuiTestObject label_Convictions_yes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_Convictions_yes"));
	}
	/**
	 * Yes: with specific test context and state.
	 *		.id : 
	 * 		.value : Yes
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		for : motoring-offense-yes
	 * 		.classIndex : RegularExpression(\d)
	 */
	protected GuiTestObject label_Convictions_yes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_Convictions_yes"), anchor, flags);
	}
	
	/**
	 * AddAConviction: with default state.
	 *		.text : Add a conviction
	 * 		.href : RegularExpression(car-insurance)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addAConviction() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addAConviction"));
	}
	/**
	 * AddAConviction: with specific test context and state.
	 *		.text : Add a conviction
	 * 		.href : RegularExpression(car-insurance)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addAConviction(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addAConviction"), anchor, flags);
	}
	
	

	protected Motor_Conviction_DetailsHelper()
	{
		setScriptName("Motor_MK2.Your__Details.Motor_Conviction_Details");
	}
	
}

