// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Home_MK2;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Pre_Payment_Confirmation</b><br>
 * Generated     : <b>2015/06/18 15:16:01</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  June 18, 2015
 * @author horned
 */
public abstract class Pre_Payment_ConfirmationHelper extends Utilities.AA_SuperHelper
{
	/**
	 * Nextsubmit: with default state.
	 *		.id : payment_nextButton
	 * 		.type : submit
	 * 		.value : Next
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_nextsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_nextsubmit"));
	}
	/**
	 * Nextsubmit: with specific test context and state.
	 *		.id : payment_nextButton
	 * 		.type : submit
	 * 		.value : Next
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_nextsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_nextsubmit"), anchor, flags);
	}
	
	/**
	 * termsAndConditionsConfirmon: with default state.
	 *		.id : termsAndConditionsConfirm
	 * 		.type : checkbox
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : termsAndConditionsConfirm
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject checkBox_termsAndConditionsCon() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_termsAndConditionsCon"));
	}
	/**
	 * termsAndConditionsConfirmon: with specific test context and state.
	 *		.id : termsAndConditionsConfirm
	 * 		.type : checkbox
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : termsAndConditionsConfirm
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject checkBox_termsAndConditionsCon(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_termsAndConditionsCon"), anchor, flags);
	}
	
	/**
	 * paymentDetails: with default state.
	 *		.id : paymentDetails
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : paymentDetails
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_paymentDetails() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_paymentDetails"));
	}
	/**
	 * paymentDetails: with specific test context and state.
	 *		.id : paymentDetails
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : paymentDetails
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_paymentDetails(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_paymentDetails"), anchor, flags);
	}
	
	/**
	 * summaryAddress: with default state.
	 *		.id : summary-address
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_summaryAddress() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_summaryAddress"));
	}
	/**
	 * summaryAddress: with specific test context and state.
	 *		.id : summary-address
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_summaryAddress(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_summaryAddress"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"), anchor, flags);
	}
	
	

	protected Pre_Payment_ConfirmationHelper()
	{
		setScriptName("Home_MK2.Pre_Payment_Confirmation");
	}
	
}

