// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Home_MK2;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Quick_Quote</b><br>
 * Generated     : <b>2015/01/15 10:35:30</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  January 15, 2015
 * @author horned
 */
public abstract class Quick_QuoteHelper extends RationalTestScript
{
	/**
	 * _1: with default state.
	 *		.id : bedrooms-one
	 * 		.value :  1 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject bed_1() 
	{
		return new GuiTestObject(
                        getMappedTestObject("bed_1"));
	}
	/**
	 * _1: with specific test context and state.
	 *		.id : bedrooms-one
	 * 		.value :  1 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject bed_1(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("bed_1"), anchor, flags);
	}
	
	/**
	 * _2: with default state.
	 *		.id : bedrooms-two
	 * 		.value :  2 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 1
	 */
	protected GuiTestObject bed_2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("bed_2"));
	}
	/**
	 * _2: with specific test context and state.
	 *		.id : bedrooms-two
	 * 		.value :  2 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 1
	 */
	protected GuiTestObject bed_2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("bed_2"), anchor, flags);
	}
	
	/**
	 * _3: with default state.
	 *		.id : bedrooms-three
	 * 		.value :  3 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 2
	 */
	protected GuiTestObject bed_3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("bed_3"));
	}
	/**
	 * _3: with specific test context and state.
	 *		.id : bedrooms-three
	 * 		.value :  3 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 2
	 */
	protected GuiTestObject bed_3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("bed_3"), anchor, flags);
	}
	
	/**
	 * _4: with default state.
	 *		.id : bedrooms-four
	 * 		.value :  4 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 3
	 */
	protected GuiTestObject bed_4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("bed_4"));
	}
	/**
	 * _4: with specific test context and state.
	 *		.id : bedrooms-four
	 * 		.value :  4 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 3
	 */
	protected GuiTestObject bed_4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("bed_4"), anchor, flags);
	}
	
	/**
	 * _5: with default state.
	 *		.id : bedrooms-five
	 * 		.value :  5 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 4
	 */
	protected GuiTestObject bed_5() 
	{
		return new GuiTestObject(
                        getMappedTestObject("bed_5"));
	}
	/**
	 * _5: with specific test context and state.
	 *		.id : bedrooms-five
	 * 		.value :  5 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 4
	 */
	protected GuiTestObject bed_5(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("bed_5"), anchor, flags);
	}
	
	/**
	 * Bungalow: with default state.
	 *		.id : property-bungalow
	 * 		.value :  Bungalow 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 4
	 */
	protected GuiTestObject bungalow() 
	{
		return new GuiTestObject(
                        getMappedTestObject("bungalow"));
	}
	/**
	 * Bungalow: with specific test context and state.
	 *		.id : property-bungalow
	 * 		.value :  Bungalow 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 4
	 */
	protected GuiTestObject bungalow(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("bungalow"), anchor, flags);
	}
	
	/**
	 * Detached: with default state.
	 *		.id : property-detached
	 * 		.value :  Detached 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 3
	 */
	protected GuiTestObject detached() 
	{
		return new GuiTestObject(
                        getMappedTestObject("detached"));
	}
	/**
	 * Detached: with specific test context and state.
	 *		.id : property-detached
	 * 		.value :  Detached 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 3
	 */
	protected GuiTestObject detached(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("detached"), anchor, flags);
	}
	
	/**
	 * FlatMaisonette: with default state.
	 *		.id : property-flat
	 * 		.value :  Flat/maisonette 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject flatMaisonette() 
	{
		return new GuiTestObject(
                        getMappedTestObject("flatMaisonette"));
	}
	/**
	 * FlatMaisonette: with specific test context and state.
	 *		.id : property-flat
	 * 		.value :  Flat/maisonette 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject flatMaisonette(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("flatMaisonette"), anchor, flags);
	}
	
	/**
	 * HMlandingPage_GetQuote: with default state.
	 *		.text : Get a quote
	 * 		.id : HMlandingPage_GetQuote
	 * 		.href : https://prelive1.theaa.com/home-membership/#/details/
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject getQuote() 
	{
		return new GuiTestObject(
                        getMappedTestObject("getQuote"));
	}
	/**
	 * HMlandingPage_GetQuote: with specific test context and state.
	 *		.text : Get a quote
	 * 		.id : HMlandingPage_GetQuote
	 * 		.href : https://prelive1.theaa.com/home-membership/#/details/
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject getQuote(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("getQuote"), anchor, flags);
	}
	
	/**
	 * HomeMembershipBoilerCoverHomeEmergencyAA: with default state.
	 *		.title : Home Membership | Boiler Cover | Home Emergency | AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(home-membership)
	 */
	protected DocumentTestObject homeMembership() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("homeMembership"));
	}
	/**
	 * HomeMembershipBoilerCoverHomeEmergencyAA: with specific test context and state.
	 *		.title : Home Membership | Boiler Cover | Home Emergency | AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(home-membership)
	 */
	protected DocumentTestObject homeMembership(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("homeMembership"), anchor, flags);
	}
	
	/**
	 * house: with default state.
	 *		.id : house
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : house
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject house_Number() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("house_Number"));
	}
	/**
	 * house: with specific test context and state.
	 *		.id : house
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : house
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject house_Number(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("house_Number"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"), anchor, flags);
	}
	
	/**
	 * No: with default state.
	 *		.id : member-false
	 * 		.value :  No 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 1
	 */
	protected GuiTestObject member_No() 
	{
		return new GuiTestObject(
                        getMappedTestObject("member_No"));
	}
	/**
	 * No: with specific test context and state.
	 *		.id : member-false
	 * 		.value :  No 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 1
	 */
	protected GuiTestObject member_No(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("member_No"), anchor, flags);
	}
	
	/**
	 * Yes: with default state.
	 *		.id : member-true
	 * 		.value :  Yes 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject member_Yes() 
	{
		return new GuiTestObject(
                        getMappedTestObject("member_Yes"));
	}
	/**
	 * Yes: with specific test context and state.
	 *		.id : member-true
	 * 		.value :  Yes 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject member_Yes(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("member_Yes"), anchor, flags);
	}
	
	/**
	 * Nextsubmit: with default state.
	 *		.id : initdetails_nextButton
	 * 		.type : submit
	 * 		.value : Next
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject nextsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("nextsubmit"));
	}
	/**
	 * Nextsubmit: with specific test context and state.
	 *		.id : initdetails_nextButton
	 * 		.type : submit
	 * 		.value : Next
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject nextsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("nextsubmit"), anchor, flags);
	}
	
	/**
	 * postcode: with default state.
	 *		.id : postcode
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : postcode
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject postCode() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("postCode"));
	}
	/**
	 * postcode: with specific test context and state.
	 *		.id : postcode
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : postcode
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject postCode(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("postCode"), anchor, flags);
	}
	
	/**
	 * SemiDetached: with default state.
	 *		.id : property-semi
	 * 		.value :  Semi-detached 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 2
	 */
	protected GuiTestObject semiDetached() 
	{
		return new GuiTestObject(
                        getMappedTestObject("semiDetached"));
	}
	/**
	 * SemiDetached: with specific test context and state.
	 *		.id : property-semi
	 * 		.value :  Semi-detached 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 2
	 */
	protected GuiTestObject semiDetached(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("semiDetached"), anchor, flags);
	}
	
	/**
	 * Terraced: with default state.
	 *		.id : property-terraced
	 * 		.value :  Terraced 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 1
	 */
	protected GuiTestObject terraced() 
	{
		return new GuiTestObject(
                        getMappedTestObject("terraced"));
	}
	/**
	 * Terraced: with specific test context and state.
	 *		.id : property-terraced
	 * 		.value :  Terraced 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 1
	 */
	protected GuiTestObject terraced(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("terraced"), anchor, flags);
	}
	
	/**
	 * headerInner: with default state.
	 *		.id : headerInner
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject title() 
	{
		return new GuiTestObject(
                        getMappedTestObject("title"));
	}
	/**
	 * headerInner: with specific test context and state.
	 *		.id : headerInner
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject title(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("title"), anchor, flags);
	}
	
	

	protected Quick_QuoteHelper()
	{
		setScriptName("Home_MK2.Quick_Quote");
	}
	
}

