// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Motor;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Proposer_Previous_Claims</b><br>
 * Generated     : <b>2014/10/17 13:50:44</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  October 17, 2014
 * @author greend1
 */
public abstract class Proposer_Previous_ClaimsHelper extends RationalTestScript
{
	/**
	 * CarInsuranceYourDetailsTheAA: with default state.
	 *		.title : Car Insurance: Your details - The AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(.*.theaa\.com/car-insurance/buy/policyholder-details.*)
	 */
	protected DocumentTestObject document_carInsuranceYourDetai() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_carInsuranceYourDetai"));
	}
	/**
	 * CarInsuranceYourDetailsTheAA: with specific test context and state.
	 *		.title : Car Insurance: Your details - The AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(.*.theaa\.com/car-insurance/buy/policyholder-details.*)
	 */
	protected DocumentTestObject document_carInsuranceYourDetai(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_carInsuranceYourDetai"), anchor, flags);
	}
	
	/**
	 * exposeMask: with default state.
	 *		.id : exposeMask
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 10
	 */
	protected GuiTestObject html_exposeMask() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exposeMask"));
	}
	/**
	 * exposeMask: with specific test context and state.
	 *		.id : exposeMask
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 10
	 */
	protected GuiTestObject html_exposeMask(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exposeMask"), anchor, flags);
	}
	
	/**
	 * AddAClaim: with default state.
	 *		.alt : Add a claim
	 * 		.id : 
	 * 		.src : https://prelive5.theaa.com/resources/images/journeys/buttons/add-claim.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_addAClaim() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_addAClaim"));
	}
	/**
	 * AddAClaim: with specific test context and state.
	 *		.alt : Add a claim
	 * 		.id : 
	 * 		.src : https://prelive5.theaa.com/resources/images/journeys/buttons/add-claim.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_addAClaim(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_addAClaim"), anchor, flags);
	}
	
	/**
	 * Continue: with default state.
	 *		.alt : Continue
	 * 		.id : 
	 * 		.src : https://prelive5.theaa.com/resources/images/journeys/buttons/continue.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_continue() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_continue"));
	}
	/**
	 * Continue: with specific test context and state.
	 *		.alt : Continue
	 * 		.id : 
	 * 		.src : https://prelive5.theaa.com/resources/images/journeys/buttons/continue.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_continue(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_continue"), anchor, flags);
	}
	
	/**
	 * AddAClaim: with default state.
	 *		.text : Add details
	 * 		.href : RegularExpression(https://.*\.theaa\.com/car-insurance/buy/policyholder-details\ ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addAClaim() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addAClaim"));
	}
	/**
	 * AddAClaim: with specific test context and state.
	 *		.text : Add details
	 * 		.href : RegularExpression(https://.*\.theaa\.com/car-insurance/buy/policyholder-details\ ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addAClaim(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addAClaim"), anchor, flags);
	}
	
	/**
	 * AddDetails: with default state.
	 *		.text : Add details
	 * 		.id : 
	 * 		.href : https://prelive1.theaa.com/car-insurance/buy/policyholder-details#
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addDetails() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addDetails"));
	}
	/**
	 * AddDetails: with specific test context and state.
	 *		.text : Add details
	 * 		.id : 
	 * 		.href : https://prelive1.theaa.com/car-insurance/buy/policyholder-details#
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addDetails(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addDetails"), anchor, flags);
	}
	
	/**
	 * claimsConfirm: with default state.
	 *		.text : Next
	 * 		.href : RegularExpression(https://prelive.*\.theaa\.com/car-insurance/buy/policyholder-d ...
	 * 		.id : claims-confirm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_claimsConfirm() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_claimsConfirm"));
	}
	/**
	 * claimsConfirm: with specific test context and state.
	 *		.text : Next
	 * 		.href : RegularExpression(https://prelive.*\.theaa\.com/car-insurance/buy/policyholder-d ...
	 * 		.id : claims-confirm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_claimsConfirm(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_claimsConfirm"), anchor, flags);
	}
	
	/**
	 * Next: with default state.
	 *		.text : Next
	 * 		.href : RegularExpression(https://prelive.*\.theaa\.com/car-insurance/buy/policyholder-d ...
	 * 		.id : claims-confirm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_next() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_next"));
	}
	/**
	 * Next: with specific test context and state.
	 *		.text : Next
	 * 		.href : RegularExpression(https://prelive.*\.theaa\.com/car-insurance/buy/policyholder-d ...
	 * 		.id : claims-confirm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_next(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_next"), anchor, flags);
	}
	
	/**
	 * aaMotorDrivers0Claims0Month: with default state.
	 *		.text : Month January February March April May June July August September October Novemb ...
	 * 		.id : claim-date-month
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.motor.drivers[0].claims[0].month
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_aaMotorDrivers0Claims0Mon() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaMotorDrivers0Claims0Mon"));
	}
	/**
	 * aaMotorDrivers0Claims0Month: with specific test context and state.
	 *		.text : Month January February March April May June July August September October Novemb ...
	 * 		.id : claim-date-month
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.motor.drivers[0].claims[0].month
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_aaMotorDrivers0Claims0Mon(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaMotorDrivers0Claims0Mon"), anchor, flags);
	}
	
	/**
	 * aaMotorDrivers0Claims0Reason: with default state.
	 *		.text : Please select Hit whilst Parked Hit in Rear Hit by Third Party TP out of side ro ...
	 * 		.id : claims-list
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.motor.drivers[0].claims[0].reason
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_aaMotorDrivers0Claims0Rea() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaMotorDrivers0Claims0Rea"));
	}
	/**
	 * aaMotorDrivers0Claims0Reason: with specific test context and state.
	 *		.text : Please select Hit whilst Parked Hit in Rear Hit by Third Party TP out of side ro ...
	 * 		.id : claims-list
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.motor.drivers[0].claims[0].reason
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_aaMotorDrivers0Claims0Rea(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaMotorDrivers0Claims0Rea"), anchor, flags);
	}
	
	/**
	 * aaMotorDrivers0Claims0Year: with default state.
	 *		.text : Year 2013 2012 2011 2010 2009 2008 2007
	 * 		.id : claim-date-year
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.motor.drivers[0].claims[0].year
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_aaMotorDrivers0Claims0Yea() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaMotorDrivers0Claims0Yea"));
	}
	/**
	 * aaMotorDrivers0Claims0Year: with specific test context and state.
	 *		.text : Year 2013 2012 2011 2010 2009 2008 2007
	 * 		.id : claim-date-year
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.motor.drivers[0].claims[0].year
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_aaMotorDrivers0Claims0Yea(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaMotorDrivers0Claims0Yea"), anchor, flags);
	}
	
	/**
	 * aaMotorDrivers0Claims0Faultfalse: with default state.
	 *		.id : fault-claim-no
	 * 		.type : radio
	 * 		.value : false
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.motor.drivers[0].claims[0].fault
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_aaMotorDrivers0Cla() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_aaMotorDrivers0Cla"));
	}
	/**
	 * aaMotorDrivers0Claims0Faultfalse: with specific test context and state.
	 *		.id : fault-claim-no
	 * 		.type : radio
	 * 		.value : false
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.motor.drivers[0].claims[0].fault
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_aaMotorDrivers0Cla(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_aaMotorDrivers0Cla"), anchor, flags);
	}
	
	/**
	 * aaMotorDrivers0Claims0PersonalInjuryfalse: with default state.
	 *		.id : personal-injury-no
	 * 		.type : radio
	 * 		.value : false
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.motor.drivers[0].claims[0].personalInjury
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_aaMotorDrivers0Cla2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_aaMotorDrivers0Cla2"));
	}
	/**
	 * aaMotorDrivers0Claims0PersonalInjuryfalse: with specific test context and state.
	 *		.id : personal-injury-no
	 * 		.type : radio
	 * 		.value : false
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : aa.motor.drivers[0].claims[0].personalInjury
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_aaMotorDrivers0Cla2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_aaMotorDrivers0Cla2"), anchor, flags);
	}
	
	/**
	 * aaMotorDrivers0Claims0Value: with default state.
	 *		.id : claim-cost
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.motor.drivers[0].claims[0].value
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_aaMotorDrivers0Claims0Val() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_aaMotorDrivers0Claims0Val"));
	}
	/**
	 * aaMotorDrivers0Claims0Value: with specific test context and state.
	 *		.id : claim-cost
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : aa.motor.drivers[0].claims[0].value
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_aaMotorDrivers0Claims0Val(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_aaMotorDrivers0Claims0Val"), anchor, flags);
	}
	
	

	protected Proposer_Previous_ClaimsHelper()
	{
		setScriptName("Motor.Proposer_Previous_Claims");
	}
	
}

