// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Home;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Boost_your_Cover</b><br>
 * Generated     : <b>2015/10/09 14:54:08</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  October 09, 2015
 * @author horned
 */
public abstract class Boost_your_CoverHelper extends Utilities.AA_SuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Back: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Back
	 */
	protected GuiTestObject button_back() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_back"));
	}
	/**
	 * Back: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Back
	 */
	protected GuiTestObject button_back(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_back"), anchor, flags);
	}
	
	/**
	 * BuyNow: with default state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.image
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buyNow() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNow"));
	}
	/**
	 * BuyNow: with specific test context and state.
	 *		.id : 
	 * 		.type : image
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.INPUT.image
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buyNow(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNow"), anchor, flags);
	}
	
	/**
	 * BuyNowsubmit: with default state.
	 *		.id : HomeInsAddonsBuyButton
	 * 		.type : submit
	 * 		.value : Buy now
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : Submit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buyNowsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNowsubmit"));
	}
	/**
	 * BuyNowsubmit: with specific test context and state.
	 *		.id : HomeInsAddonsBuyButton
	 * 		.type : submit
	 * 		.value : Buy now
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : Submit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buyNowsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNowsubmit"), anchor, flags);
	}
	
	/**
	 * BuyNowsubmit: with default state.
	 *		.id : HomeInsAddonsBuyButton
	 * 		.type : submit
	 * 		.value : Buy now
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : Submit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buyNowsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNowsubmit2"));
	}
	/**
	 * BuyNowsubmit: with specific test context and state.
	 *		.id : HomeInsAddonsBuyButton
	 * 		.type : submit
	 * 		.value : Buy now
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : Submit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buyNowsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNowsubmit2"), anchor, flags);
	}
	
	/**
	 * BuyNowsubmit: with default state.
	 *		.id : HomeInsQuoteBuyButton
	 * 		.type : submit
	 * 		.value : Buy now
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : quotePurchase
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_buyNowsubmit3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNowsubmit3"));
	}
	/**
	 * BuyNowsubmit: with specific test context and state.
	 *		.id : HomeInsQuoteBuyButton
	 * 		.type : submit
	 * 		.value : Buy now
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : quotePurchase
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_buyNowsubmit3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNowsubmit3"), anchor, flags);
	}
	
	/**
	 * BuyNowsubmit: with default state.
	 *		.id : HomeInsQuoteBuyButton
	 * 		.type : submit
	 * 		.value : Buy now
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : quotePurchase
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_buyNowsubmit4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNowsubmit4"));
	}
	/**
	 * BuyNowsubmit: with specific test context and state.
	 *		.id : HomeInsQuoteBuyButton
	 * 		.type : submit
	 * 		.value : Buy now
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : quotePurchase
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_buyNowsubmit4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buyNowsubmit4"), anchor, flags);
	}
	
	/**
	 * Yessubmit: with default state.
	 *		.id : yes_image
	 * 		.type : submit
	 * 		.value : Yes
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_yessubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yessubmit"));
	}
	/**
	 * Yessubmit: with specific test context and state.
	 *		.id : yes_image
	 * 		.type : submit
	 * 		.value : Yes
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject button_yessubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yessubmit"), anchor, flags);
	}
	
	/**
	 * includeHomeLegalExpensesY: with default state.
	 *		.id : LegalExpensesCover
	 * 		.type : checkbox
	 * 		.value : Y
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : includeHomeLegalExpenses
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_includeHomeLegalExpen() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_includeHomeLegalExpen"));
	}
	/**
	 * includeHomeLegalExpensesY: with specific test context and state.
	 *		.id : LegalExpensesCover
	 * 		.type : checkbox
	 * 		.value : Y
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : includeHomeLegalExpenses
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_includeHomeLegalExpen(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_includeHomeLegalExpen"), anchor, flags);
	}
	
	/**
	 * HomeInsuranceCheckYourDetailsTheAA: with default state.
	 *		.title : Home Insurance : Check your details - The AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.theaa.com/home-insurance/viewAssumptions.do
	 */
	protected DocumentTestObject document_homeInsuranceCheckYou() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homeInsuranceCheckYou"));
	}
	/**
	 * HomeInsuranceCheckYourDetailsTheAA: with specific test context and state.
	 *		.title : Home Insurance : Check your details - The AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.theaa.com/home-insurance/viewAssumptions.do
	 */
	protected DocumentTestObject document_homeInsuranceCheckYou(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homeInsuranceCheckYou"), anchor, flags);
	}
	
	/**
	 * TheAAPaymentGateway: with default state.
	 *		.title : The AA: Payment Gateway
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://payments.theaa.com/start
	 */
	protected DocumentTestObject document_theAAPaymentGateway() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_theAAPaymentGateway"));
	}
	/**
	 * TheAAPaymentGateway: with specific test context and state.
	 *		.title : The AA: Payment Gateway
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://payments.theaa.com/start
	 */
	protected DocumentTestObject document_theAAPaymentGateway(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_theAAPaymentGateway"), anchor, flags);
	}
	
	/**
	 * LegalExpensesCover£2599GetExpertLegalHelpWhenYouNeed: with default state.
	 *		.id : 
	 * 		.value : RegularExpression(  Legal Expenses Cover.*)
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_legalExpensesCover£2599G() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_legalExpensesCover£2599G"));
	}
	/**
	 * LegalExpensesCover£2599GetExpertLegalHelpWhenYouNeed: with specific test context and state.
	 *		.id : 
	 * 		.value : RegularExpression(  Legal Expenses Cover.*)
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_legalExpensesCover£2599G(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_legalExpensesCover£2599G"), anchor, flags);
	}
	
	/**
	 * LegalExpensesCover£2599GetExpertLegalHelpWhenYouNeed: with default state.
	 *		.id : 
	 * 		.value : RegularExpression(  Legal Expenses Cover £.*)
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_legalExpensesCover£2599G2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_legalExpensesCover£2599G2"));
	}
	/**
	 * LegalExpensesCover£2599GetExpertLegalHelpWhenYouNeed: with specific test context and state.
	 *		.id : 
	 * 		.value : RegularExpression(  Legal Expenses Cover £.*)
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_legalExpensesCover£2599G2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_legalExpensesCover£2599G2"), anchor, flags);
	}
	
	/**
	 * LegalExpensesCover£2599WhatWouldYouDoIfYouWantedTo: with default state.
	 *		.id : 
	 * 		.value : RegularExpression(Home Legal Expenses – £.*\r\n\r\nGet expert legal help when yo ...
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_legalExpensesCover£2599W() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_legalExpensesCover£2599W"));
	}
	/**
	 * LegalExpensesCover£2599WhatWouldYouDoIfYouWantedTo: with specific test context and state.
	 *		.id : 
	 * 		.value : RegularExpression(Home Legal Expenses – £.*\r\n\r\nGet expert legal help when yo ...
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_legalExpensesCover£2599W(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_legalExpensesCover£2599W"), anchor, flags);
	}
	
	/**
	 * AmendAddress: with default state.
	 *		.text : Amend address
	 * 		.id : 
	 * 		.href : RegularExpression(https://.*\.theaa\.com/home-insurance/viewMainDetails\.do\#abo ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_amendAddress() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_amendAddress"));
	}
	/**
	 * AmendAddress: with specific test context and state.
	 *		.text : Amend address
	 * 		.id : 
	 * 		.href : RegularExpression(https://.*\.theaa\.com/home-insurance/viewMainDetails\.do\#abo ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_amendAddress(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_amendAddress"), anchor, flags);
	}
	
	

	protected Boost_your_CoverHelper()
	{
		setScriptName("Home.Boost_your_Cover");
	}
	
}

