// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Motor_MK2.Your__Quote;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Policy_Excess</b><br>
 * Generated     : <b>2015/07/07 08:53:07</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  July 07, 2015
 * @author horned
 */
public abstract class Policy_ExcessHelper extends Utilities.AA_SuperHelper
{
	/**
	 * CarInsuranceYourQuoteTheAA: with default state.
	 *		.title : RegularExpression(Your quote)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(car-insurance)
	 */
	protected DocumentTestObject document_carInsuranceYourQuote() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_carInsuranceYourQuote"));
	}
	/**
	 * CarInsuranceYourQuoteTheAA: with specific test context and state.
	 *		.title : RegularExpression(Your quote)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(car-insurance)
	 */
	protected DocumentTestObject document_carInsuranceYourQuote(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_carInsuranceYourQuote"), anchor, flags);
	}
	
	/**
	 * volxsContainer: with default state.
	 *		.id : volxs-container
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 3
	 */
	protected GuiTestObject html_volxsContainer() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_volxsContainer"));
	}
	/**
	 * volxsContainer: with specific test context and state.
	 *		.id : volxs-container
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 3
	 */
	protected GuiTestObject html_volxsContainer(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_volxsContainer"), anchor, flags);
	}
	
	/**
	 * xsTable: with default state.
	 *		.id : xs-table
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_xsTable() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_xsTable"));
	}
	/**
	 * xsTable: with specific test context and state.
	 *		.id : xs-table
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_xsTable(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_xsTable"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"), anchor, flags);
	}
	
	/**
	 * ViewFullExcessDetails: with default state.
	 *		.text : View full excess details
	 * 		.href : RegularExpression(car-insurance)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_viewFullExcessDetails() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewFullExcessDetails"));
	}
	/**
	 * ViewFullExcessDetails: with specific test context and state.
	 *		.text : View full excess details
	 * 		.href : RegularExpression(car-insurance)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_viewFullExcessDetails(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_viewFullExcessDetails"), anchor, flags);
	}
	
	/**
	 * aaMotorVoluntaryExcessCode: with default state.
	 *		.text : Please select £Nil £50 £75 £100 £125 £150 £200 £250 £300 £350 £400 £450 £500
	 * 		.id : voluntary-excess
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.motor.voluntaryExcess.code
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_aaMotorVoluntaryExcessCod() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaMotorVoluntaryExcessCod"));
	}
	/**
	 * aaMotorVoluntaryExcessCode: with specific test context and state.
	 *		.text : Please select £Nil £50 £75 £100 £125 £150 £200 £250 £300 £350 £400 £450 £500
	 * 		.id : voluntary-excess
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : aa.motor.voluntaryExcess.code
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_aaMotorVoluntaryExcessCod(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_aaMotorVoluntaryExcessCod"), anchor, flags);
	}
	
	

	protected Policy_ExcessHelper()
	{
		setScriptName("Motor_MK2.Your__Quote.Policy_Excess");
	}
	
}

