// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Aggregators.Home;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Number_Bedrooms</b><br>
 * Generated     : <b>2015/06/23 10:17:15</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  June 23, 2015
 * @author horned
 */
public abstract class Number_BedroomsHelper extends Utilities.AA_SuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * HomeInsuranceYouAndYourHomeTheAA: with default state.
	 *		.title : RegularExpression(Home Insurance)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(home-insurance)
	 */
	protected DocumentTestObject document_homeInsuranceYouAndYo() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homeInsuranceYouAndYo"));
	}
	/**
	 * HomeInsuranceYouAndYourHomeTheAA: with specific test context and state.
	 *		.title : RegularExpression(Home Insurance)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(home-insurance)
	 */
	protected DocumentTestObject document_homeInsuranceYouAndYo(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homeInsuranceYouAndYo"), anchor, flags);
	}
	
	/**
	 * NOOFBEDROOMS1: with default state.
	 *		.id : NOOFBEDROOMS1
	 * 		.type : radio
	 * 		.value : 1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : NOOFBEDROOMS
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_noofbedroomS1() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_noofbedroomS1"));
	}
	/**
	 * NOOFBEDROOMS1: with specific test context and state.
	 *		.id : NOOFBEDROOMS1
	 * 		.type : radio
	 * 		.value : 1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : NOOFBEDROOMS
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_noofbedroomS1(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_noofbedroomS1"), anchor, flags);
	}
	
	/**
	 * NOOFBEDROOMS2: with default state.
	 *		.id : NOOFBEDROOMS2
	 * 		.type : radio
	 * 		.value : 2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : NOOFBEDROOMS
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_noofbedroomS2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_noofbedroomS2"));
	}
	/**
	 * NOOFBEDROOMS2: with specific test context and state.
	 *		.id : NOOFBEDROOMS2
	 * 		.type : radio
	 * 		.value : 2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : NOOFBEDROOMS
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_noofbedroomS2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_noofbedroomS2"), anchor, flags);
	}
	
	/**
	 * NOOFBEDROOMS3: with default state.
	 *		.id : NOOFBEDROOMS3
	 * 		.type : radio
	 * 		.value : 3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : NOOFBEDROOMS
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_noofbedroomS3() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_noofbedroomS3"));
	}
	/**
	 * NOOFBEDROOMS3: with specific test context and state.
	 *		.id : NOOFBEDROOMS3
	 * 		.type : radio
	 * 		.value : 3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : NOOFBEDROOMS
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_noofbedroomS3(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_noofbedroomS3"), anchor, flags);
	}
	
	/**
	 * NOOFBEDROOMS4: with default state.
	 *		.id : NOOFBEDROOMS4
	 * 		.type : radio
	 * 		.value : 4
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : NOOFBEDROOMS
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_noofbedroomS4() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_noofbedroomS4"));
	}
	/**
	 * NOOFBEDROOMS4: with specific test context and state.
	 *		.id : NOOFBEDROOMS4
	 * 		.type : radio
	 * 		.value : 4
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : NOOFBEDROOMS
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_noofbedroomS4(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_noofbedroomS4"), anchor, flags);
	}
	
	/**
	 * NOOFBEDROOMS5: with default state.
	 *		.id : NOOFBEDROOMS5
	 * 		.type : radio
	 * 		.value : 5
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : NOOFBEDROOMS
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_noofbedroomS5() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_noofbedroomS5"));
	}
	/**
	 * NOOFBEDROOMS5: with specific test context and state.
	 *		.id : NOOFBEDROOMS5
	 * 		.type : radio
	 * 		.value : 5
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : NOOFBEDROOMS
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_noofbedroomS5(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_noofbedroomS5"), anchor, flags);
	}
	
	

	protected Number_BedroomsHelper()
	{
		setScriptName("Aggregators.Home.Number_Bedrooms");
	}
	
}

