// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Aggregators.Home;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Verify_Home_Common_Content</b><br>
 * Generated     : <b>2015/05/11 10:30:54</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  May 11, 2015
 * @author horned
 */
public abstract class Verify_Home_Common_ContentHelper extends Utilities.AA_SuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Back: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Back
	 */
	protected GuiTestObject button_back() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_back"));
	}
	/**
	 * Back: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Back
	 */
	protected GuiTestObject button_back(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_back"), anchor, flags);
	}
	
	/**
	 * HomeInsuranceThisPageHasTimedOutTheAA: with default state.
	 *		.title : Home Insurance : This page has timed out - The AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://prelive1.theaa.com/services/insuranceandfinance/home/n_timeout.jsp
	 */
	protected DocumentTestObject document_homeInsuranceThisPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homeInsuranceThisPage"));
	}
	/**
	 * HomeInsuranceThisPageHasTimedOutTheAA: with specific test context and state.
	 *		.title : Home Insurance : This page has timed out - The AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://prelive1.theaa.com/services/insuranceandfinance/home/n_timeout.jsp
	 */
	protected DocumentTestObject document_homeInsuranceThisPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homeInsuranceThisPage"), anchor, flags);
	}
	
	/**
	 * HomeInsuranceThisPageHasTimedOutTheAA: with default state.
	 *		.title : Home Insurance : This page has timed out - The AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://prelive1.theaa.com/home-insurance/timeout.do
	 */
	protected DocumentTestObject document_homeInsuranceThisPage2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homeInsuranceThisPage2"));
	}
	/**
	 * HomeInsuranceThisPageHasTimedOutTheAA: with specific test context and state.
	 *		.title : Home Insurance : This page has timed out - The AA
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://prelive1.theaa.com/home-insurance/timeout.do
	 */
	protected DocumentTestObject document_homeInsuranceThisPage2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homeInsuranceThisPage2"), anchor, flags);
	}
	
	/**
	 * aside: with default state.
	 *		.id : aside
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_aside() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_aside"));
	}
	/**
	 * aside: with specific test context and state.
	 *		.id : aside
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_aside(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_aside"), anchor, flags);
	}
	
	/**
	 * main: with default state.
	 *		.id : main
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_main() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_main"));
	}
	/**
	 * main: with specific test context and state.
	 *		.id : main
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_main(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_main"), anchor, flags);
	}
	
	/**
	 * AnnualPayment: with default state.
	 *		.id : PayOnePaymentLabel
	 * 		.value :  Annual payment 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 1
	 */
	protected GuiTestObject label_annualPayment() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_annualPayment"));
	}
	/**
	 * AnnualPayment: with specific test context and state.
	 *		.id : PayOnePaymentLabel
	 * 		.value :  Annual payment 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 1
	 */
	protected GuiTestObject label_annualPayment(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_annualPayment"), anchor, flags);
	}
	
	/**
	 * PayMonthly: with default state.
	 *		.id : PayInstalmentsLabel
	 * 		.value :  Pay monthly 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_payMonthly() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_payMonthly"));
	}
	/**
	 * PayMonthly: with specific test context and state.
	 *		.id : PayInstalmentsLabel
	 * 		.value :  Pay monthly 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_payMonthly(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_payMonthly"), anchor, flags);
	}
	
	

	protected Verify_Home_Common_ContentHelper()
	{
		setScriptName("Aggregators.Home.Verify_Home_Common_Content");
	}
	
}

