// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Mobile_Devices.IOS.Function_Area.Breakdown_Cover.Breakdown_Cover;
import Utilities.AA_SuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>BreakDown_Cover</b><br>
 * Generated     : <b>2015/10/30 13:28:06</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  October 30, 2015
 * @author horned
 */
public abstract class BreakDown_CoverHelper extends Utilities.AA_SuperHelper
{
	/**
	 * Continuesubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Continue
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : nextPage
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_continuesubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_continuesubmit"));
	}
	/**
	 * Continuesubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Continue
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : nextPage
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_continuesubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_continuesubmit"), anchor, flags);
	}
	
	/**
	 * Continuesubmit: with default state.
	 *		.id : make-model-select
	 * 		.type : submit
	 * 		.value : Continue
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_continuesubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_continuesubmit2"));
	}
	/**
	 * Continuesubmit: with specific test context and state.
	 *		.id : make-model-select
	 * 		.type : submit
	 * 		.value : Continue
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_continuesubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_continuesubmit2"), anchor, flags);
	}
	
	/**
	 * UpdateCoversubmit: with default state.
	 *		.id : button-confirm-cover
	 * 		.type : submit
	 * 		.value : Update cover
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_updateCoversubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_updateCoversubmit"));
	}
	/**
	 * UpdateCoversubmit: with specific test context and state.
	 *		.id : button-confirm-cover
	 * 		.type : submit
	 * 		.value : Update cover
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_updateCoversubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_updateCoversubmit"), anchor, flags);
	}
	
	/**
	 * UpdateYourQuotesubmit: with default state.
	 *		.id : button-vbc
	 * 		.type : submit
	 * 		.defaultValue : Update your quote
	 * 		.value : Update your quote
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_updateYourQuotesubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_updateYourQuotesubmit"));
	}
	/**
	 * UpdateYourQuotesubmit: with specific test context and state.
	 *		.id : button-vbc
	 * 		.type : submit
	 * 		.defaultValue : Update your quote
	 * 		.value : Update your quote
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_updateYourQuotesubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_updateYourQuotesubmit"), anchor, flags);
	}
	
	/**
	 * UpdateYourQuotesubmit: with default state.
	 *		.id : button-vbc
	 * 		.type : submit
	 * 		.value : Update your quote
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_updateYourQuotesubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_updateYourQuotesubmit2"));
	}
	/**
	 * UpdateYourQuotesubmit: with specific test context and state.
	 *		.id : button-vbc
	 * 		.type : submit
	 * 		.value : Update your quote
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_updateYourQuotesubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_updateYourQuotesubmit2"), anchor, flags);
	}
	
	/**
	 * close: with default state.
	 *		.alt : close
	 * 		.id : 
	 * 		.src : RegularExpression(aa-cookies)
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject cookies_image_close() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("cookies_image_close"));
	}
	/**
	 * close: with specific test context and state.
	 *		.alt : close
	 * 		.id : 
	 * 		.src : RegularExpression(aa-cookies)
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject cookies_image_close(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("cookies_image_close"), anchor, flags);
	}
	
	/**
	 * UKBreakdownCoverViewAndChooseYourCoverAA: with default state.
	 *		.title : RegularExpression(Breakdown Cover)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(breakdown-cover)
	 */
	protected DocumentTestObject document_ukBreakdownCoverViewA() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ukBreakdownCoverViewA"));
	}
	/**
	 * UKBreakdownCoverViewAndChooseYourCoverAA: with specific test context and state.
	 *		.title : RegularExpression(Breakdown Cover)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(breakdown-cover)
	 */
	protected DocumentTestObject document_ukBreakdownCoverViewA(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ukBreakdownCoverViewA"), anchor, flags);
	}
	
	/**
	 * optionsForm: with default state.
	 *		.id : roadapp
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : optionsForm
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_optionsForm() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_optionsForm"));
	}
	/**
	 * optionsForm: with specific test context and state.
	 *		.id : roadapp
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : optionsForm
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_optionsForm(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_optionsForm"), anchor, flags);
	}
	
	/**
	 * sorconline_form: with default state.
	 *		.id : sorconline_form
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_sorconline_form() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_sorconline_form"));
	}
	/**
	 * sorconline_form: with specific test context and state.
	 *		.id : sorconline_form
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_sorconline_form(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_sorconline_form"), anchor, flags);
	}
	
	/**
	 * homeStart: with default state.
	 *		.id : homeStart
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 2
	 */
	protected GuiTestObject html_homeStart() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_homeStart"));
	}
	/**
	 * homeStart: with specific test context and state.
	 *		.id : homeStart
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 2
	 */
	protected GuiTestObject html_homeStart(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_homeStart"), anchor, flags);
	}
	
	/**
	 * monthlypricevalue: with default state.
	 *		.id : monthlypricevalue
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_monthlypricevalue() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_monthlypricevalue"));
	}
	/**
	 * monthlypricevalue: with specific test context and state.
	 *		.id : monthlypricevalue
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_monthlypricevalue(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_monthlypricevalue"), anchor, flags);
	}
	
	/**
	 * mvtTable2: with default state.
	 *		.id : mvt-table2
	 * 		.title : 
	 * 		.class : Html.SECTION
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_mvtTable2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_mvtTable2"));
	}
	/**
	 * mvtTable2: with specific test context and state.
	 *		.id : mvt-table2
	 * 		.title : 
	 * 		.class : Html.SECTION
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_mvtTable2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_mvtTable2"), anchor, flags);
	}
	
	/**
	 * pricevalue: with default state.
	 *		.id : pricevalue
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_pricevalue() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_pricevalue"));
	}
	/**
	 * pricevalue: with specific test context and state.
	 *		.id : pricevalue
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_pricevalue(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_pricevalue"), anchor, flags);
	}
	
	/**
	 * relay: with default state.
	 *		.id : relay
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_relay() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_relay"));
	}
	/**
	 * relay: with specific test context and state.
	 *		.id : relay
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_relay(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_relay"), anchor, flags);
	}
	
	/**
	 * stayMobile: with default state.
	 *		.id : stayMobile
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 3
	 */
	protected GuiTestObject html_stayMobile() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_stayMobile"));
	}
	/**
	 * stayMobile: with specific test context and state.
	 *		.id : stayMobile
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 3
	 */
	protected GuiTestObject html_stayMobile(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_stayMobile"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject iE(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("iE"), anchor, flags);
	}
	
	/**
	 * _1Year: with default state.
	 *		.id : 
	 * 		.value : 1 year
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_1Year() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_1Year"));
	}
	/**
	 * _1Year: with specific test context and state.
	 *		.id : 
	 * 		.value : 1 year
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_1Year(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_1Year"), anchor, flags);
	}
	
	/**
	 * AddThisOption: with default state.
	 *		.id : breakdownRepairCoverLabel
	 * 		.value : Add this option
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_addThisOption() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_addThisOption"));
	}
	/**
	 * AddThisOption: with specific test context and state.
	 *		.id : breakdownRepairCoverLabel
	 * 		.value : Add this option
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_addThisOption(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_addThisOption"), anchor, flags);
	}
	
	/**
	 * Monthly: with default state.
	 *		.id : 
	 * 		.value : Monthly
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 1
	 */
	protected GuiTestObject label_monthly() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_monthly"));
	}
	/**
	 * Monthly: with specific test context and state.
	 *		.id : 
	 * 		.value : Monthly
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 1
	 */
	protected GuiTestObject label_monthly(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_monthly"), anchor, flags);
	}
	
	/**
	 * Mr: with default state.
	 *		.id : 
	 * 		.value : Mr
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 3
	 */
	protected GuiTestObject label_mr() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mr"));
	}
	/**
	 * Mr: with specific test context and state.
	 *		.id : 
	 * 		.value : Mr
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 3
	 */
	protected GuiTestObject label_mr(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_mr"), anchor, flags);
	}
	
	/**
	 * AddAVehicle: with default state.
	 *		.text : Add a vehicle
	 * 		.href : RegularExpression(breakdown-cover)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addAVehicle() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addAVehicle"));
	}
	/**
	 * AddAVehicle: with specific test context and state.
	 *		.text : Add a vehicle
	 * 		.href : RegularExpression(breakdown-cover)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_addAVehicle(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_addAVehicle"), anchor, flags);
	}
	
	/**
	 * BuyNow: with default state.
	 *		.text : Buy now
	 * 		.href : RegularExpression(breakdown-cover/uk-breakdown/)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_buyNow() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buyNow"));
	}
	/**
	 * BuyNow: with specific test context and state.
	 *		.text : Buy now
	 * 		.href : RegularExpression(breakdown-cover/uk-breakdown/)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_buyNow(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buyNow"), anchor, flags);
	}
	
	/**
	 * BuyNow: with default state.
	 *		.text : Buy now
	 * 		.href : RegularExpression(basic-breakdown-cover)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_buyNow2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buyNow2"));
	}
	/**
	 * BuyNow: with specific test context and state.
	 *		.text : Buy now
	 * 		.href : RegularExpression(basic-breakdown-cover)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_buyNow2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buyNow2"), anchor, flags);
	}
	
	/**
	 * BuyNow£115: with default state.
	 *		.text : Buy now £115
	 * 		.href : RegularExpression(breakdown-cover/uk-breakdown)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_buyNow£115() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buyNow£115"));
	}
	/**
	 * BuyNow£115: with specific test context and state.
	 *		.text : Buy now £115
	 * 		.href : RegularExpression(breakdown-cover/uk-breakdown)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_buyNow£115(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buyNow£115"), anchor, flags);
	}
	
	/**
	 * BuyNow£155: with default state.
	 *		.text : Buy now £155
	 * 		.href : RegularExpression(breakdown-cover/uk-breakdown)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_buyNow£155() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buyNow£155"));
	}
	/**
	 * BuyNow£155: with specific test context and state.
	 *		.text : Buy now £155
	 * 		.href : RegularExpression(breakdown-cover/uk-breakdown)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_buyNow£155(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buyNow£155"), anchor, flags);
	}
	
	/**
	 * BuyNow£85: with default state.
	 *		.text : Buy now £85
	 * 		.href : RegularExpression(breakdown-cover/uk-breakdown)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_buyNow£85() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buyNow£85"));
	}
	/**
	 * BuyNow£85: with specific test context and state.
	 *		.text : Buy now £85
	 * 		.href : RegularExpression(breakdown-cover/uk-breakdown)
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_buyNow£85(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buyNow£85"), anchor, flags);
	}
	
	/**
	 * vehReg: with default state.
	 *		.id : vehReg1
	 * 		.type : text
	 * 		.className : num-plate
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : vehReg
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_vehReg() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_vehReg"));
	}
	/**
	 * vehReg: with specific test context and state.
	 *		.id : vehReg1
	 * 		.type : text
	 * 		.className : num-plate
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : vehReg
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_vehReg(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_vehReg"), anchor, flags);
	}
	
	/**
	 * vehReg: with default state.
	 *		.id : RegularExpression(vehReg)
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : vehReg
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_vehReg2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_vehReg2"));
	}
	/**
	 * vehReg: with specific test context and state.
	 *		.id : RegularExpression(vehReg)
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : vehReg
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_vehReg2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_vehReg2"), anchor, flags);
	}
	
	

	protected BreakDown_CoverHelper()
	{
		setScriptName("Mobile_Devices.IOS.Function_Area.Breakdown_Cover.Breakdown_Cover.BreakDown_Cover");
	}
	
}

